// <auto-generated>
// <copyright file="Characters.CharacterCreatorInterfaces.cs" company="jothay.com">
// Copyright (c) 2015 Jothay Tech, Inc. All rights reserved.
// </copyright>
// <summary>Declares the CharacterCreator interfaces including Entity, Model, Search Model, Mapper,
// Repository and Business Workflow in the appropriate namespaces.</summary>
// <remarks>This file was auto-generated using InterfaceFileMaster.tt in
// ComicVineScraper.API\CodeGenerator</remarks>
// </auto-generated>
// ReSharper disable RedundantUsingDirective, UnusedMemberInSuper.Global
namespace ComicVineScraper.API.Interfaces.DataModels
{
    using System;
    using System.Collections.Generic;

    public interface ICharacterCreator : IEntity
    {
        // CharacterCreator Properties
        // <None>
        // Related Objects
        int CharacterId { get; set; }
        ICharacter Character { get; set; }
        int CreatorId { get; set; }
        IPerson Creator { get; set; }
        // Associated Objects
        // <None>
    }
}

namespace ComicVineScraper.API.Interfaces.Models
{
    using System;
    using System.Collections.Generic;

    public interface ICharacterCreatorModel : IEntityModel
    {
        // CharacterCreator Properties
        // <None>
        // Related Objects
        int CharacterId { get; set; }
        ICharacterModel Character { get; set; }
        int CreatorId { get; set; }
        IPersonModel Creator { get; set; }
        // Associated Objects
        // <None>
    }
}

namespace ComicVineScraper.API.Interfaces.SearchModels
{
    public interface ICharacterCreatorSearchModel : IEntitySearchModel
    {
        int? CharacterId { get; set; }
        string CharacterCustomKey { get; set; }
        string CharacterApiDetailUrl { get; set; }
        string CharacterSiteDetailUrl { get; set; }
        string CharacterName { get; set; }
        string CharacterShortDescription { get; set; }
        string CharacterDescription { get; set; }
        int? CreatorId { get; set; }
        string CreatorCustomKey { get; set; }
        string CreatorApiDetailUrl { get; set; }
        string CreatorSiteDetailUrl { get; set; }
        string CreatorName { get; set; }
        string CreatorShortDescription { get; set; }
        string CreatorDescription { get; set; }
    }
}

namespace ComicVineScraper.API.Interfaces.Mappers
{
    public interface ICharacterCreatorMapper
        : IMapper<
            DataModels.ICharacterCreator,
            Models.ICharacterCreatorModel,
            SearchModels.ICharacterCreatorSearchModel>
    {
    }
}

namespace ComicVineScraper.API.Interfaces.Repositories
{
    public interface ICharacterCreatorsRepository
        : IRepositoryBase
        , IRepository<DataModels.ICharacterCreator, SearchModels.ICharacterCreatorSearchModel>
    {
    }
}

namespace ComicVineScraper.API.Interfaces.BusinessWorkflows
{
    public interface ICharacterCreatorsBusinessWorkflow
        : IBusinessWorkflow<Models.ICharacterCreatorModel, SearchModels.ICharacterCreatorSearchModel>
    {
    }
}
