// <auto-generated>
// <copyright file="Powers.PowerInterfaces.cs" company="jothay.com">
// Copyright (c) 2015 Jothay Tech, Inc. All rights reserved.
// </copyright>
// <summary>Declares the Power interfaces including Entity, Model, Search Model, Mapper,
// Repository and Business Workflow in the appropriate namespaces.</summary>
// <remarks>This file was auto-generated using InterfaceFileMaster.tt in
// ComicVineScraper.API\CodeGenerator</remarks>
// </auto-generated>
// ReSharper disable RedundantUsingDirective, UnusedMemberInSuper.Global
namespace ComicVineScraper.API.Interfaces.DataModels
{
    using System;
    using System.Collections.Generic;

    public interface IPower : INameableEntity
    {
        // Power Properties
        // <None>
        // Related Objects
        // <None>
        // Associated Objects
        ICollection<ICharacterPower> CharacterPowers { get; set; }
        ICollection<IPowerAlias> PowerAliases { get; set; }
    }
}

namespace ComicVineScraper.API.Interfaces.Models
{
    using System;
    using System.Collections.Generic;

    public interface IPowerModel : INameableEntityModel
    {
        // Power Properties
        // <None>
        // Related Objects
        // <None>
        // Associated Objects
        List<ICharacterPowerModel> CharacterPowers { get; set; }
        List<IPowerAliasModel> PowerAliases { get; set; }
    }
}

namespace ComicVineScraper.API.Interfaces.SearchModels
{
    public interface IPowerSearchModel : INameableEntitySearchModel
    {
    }
}

namespace ComicVineScraper.API.Interfaces.Mappers
{
    public interface IPowerMapper
        : IMapper<
            DataModels.IPower,
            Models.IPowerModel,
            SearchModels.IPowerSearchModel>
    {
    }
}

namespace ComicVineScraper.API.Interfaces.Repositories
{
    public interface IPowersRepository
        : IRepositoryBase
        , IRepository<DataModels.IPower, SearchModels.IPowerSearchModel>
    {
    }
}

namespace ComicVineScraper.API.Interfaces.BusinessWorkflows
{
    public interface IPowersBusinessWorkflow
        : IBusinessWorkflow<Models.IPowerModel, SearchModels.IPowerSearchModel>
    {
    }
}
