// <auto-generated>
// <copyright file="Volumes.VolumeCharacterInterfaces.cs" company="jothay.com">
// Copyright (c) 2015 Jothay Tech, Inc. All rights reserved.
// </copyright>
// <summary>Declares the VolumeCharacter interfaces including Entity, Model, Search Model, Mapper,
// Repository and Business Workflow in the appropriate namespaces.</summary>
// <remarks>This file was auto-generated using InterfaceFileMaster.tt in
// ComicVineScraper.API\CodeGenerator</remarks>
// </auto-generated>
// ReSharper disable RedundantUsingDirective, UnusedMemberInSuper.Global
namespace ComicVineScraper.API.Interfaces.DataModels
{
    using System;
    using System.Collections.Generic;

    public interface IVolumeCharacter : IEntity
    {
        // VolumeCharacter Properties
        // <None>
        // Related Objects
        int VolumeId { get; set; }
        IVolume Volume { get; set; }
        int CharacterId { get; set; }
        ICharacter Character { get; set; }
        // Associated Objects
        // <None>
    }
}

namespace ComicVineScraper.API.Interfaces.Models
{
    using System;
    using System.Collections.Generic;

    public interface IVolumeCharacterModel : IEntityModel
    {
        // VolumeCharacter Properties
        // <None>
        // Related Objects
        int VolumeId { get; set; }
        IVolumeModel Volume { get; set; }
        int CharacterId { get; set; }
        ICharacterModel Character { get; set; }
        // Associated Objects
        // <None>
    }
}

namespace ComicVineScraper.API.Interfaces.SearchModels
{
    public interface IVolumeCharacterSearchModel : IEntitySearchModel
    {
        int? VolumeId { get; set; }
        string VolumeCustomKey { get; set; }
        string VolumeApiDetailUrl { get; set; }
        string VolumeSiteDetailUrl { get; set; }
        string VolumeName { get; set; }
        string VolumeShortDescription { get; set; }
        string VolumeDescription { get; set; }
        int? CharacterId { get; set; }
        string CharacterCustomKey { get; set; }
        string CharacterApiDetailUrl { get; set; }
        string CharacterSiteDetailUrl { get; set; }
        string CharacterName { get; set; }
        string CharacterShortDescription { get; set; }
        string CharacterDescription { get; set; }
    }
}

namespace ComicVineScraper.API.Interfaces.Mappers
{
    public interface IVolumeCharacterMapper
        : IMapper<
            DataModels.IVolumeCharacter,
            Models.IVolumeCharacterModel,
            SearchModels.IVolumeCharacterSearchModel>
    {
    }
}

namespace ComicVineScraper.API.Interfaces.Repositories
{
    public interface IVolumeCharactersRepository
        : IRepositoryBase
        , IRepository<DataModels.IVolumeCharacter, SearchModels.IVolumeCharacterSearchModel>
    {
    }
}

namespace ComicVineScraper.API.Interfaces.BusinessWorkflows
{
    public interface IVolumeCharactersBusinessWorkflow
        : IBusinessWorkflow<Models.IVolumeCharacterModel, SearchModels.IVolumeCharacterSearchModel>
    {
    }
}
