// <auto-generated>
// <copyright file="Concepts.ConceptIssueInterfaces.cs" company="jothay.com">
// Copyright (c) 2015 Jothay Tech, Inc. All rights reserved.
// </copyright>
// <summary>Declares the ConceptIssue interfaces including Entity, Model, Search Model, Mapper,
// Repository and Business Workflow in the appropriate namespaces.</summary>
// <remarks>This file was auto-generated using InterfaceFileMaster.tt in
// ComicVine.API\Interfaces\CodeGenerator</remarks>
// </auto-generated>
// ReSharper disable RedundantUsingDirective, UnusedMemberInSuper.Global
namespace ComicVine.API.Interfaces.DataModels
{
    using System;
    using System.Collections.Generic;

    public interface IConceptIssue : IEntity
    {
        // ConceptIssue Properties
        // <None>
        // Related Objects
        int ConceptId { get; set; }
        IConcept Concept { get; set; }
        int IssueId { get; set; }
        IIssue Issue { get; set; }
        // Associated Objects
        // <None>
    }
}

namespace ComicVine.API.Interfaces.Models
{
    using System;
    using System.Collections.Generic;

    public interface IConceptIssueModel : IEntityModel
    {
        // ConceptIssue Properties
        // <None>
        // Related Objects
        int ConceptId { get; set; }
        IConceptModel Concept { get; set; }
        int IssueId { get; set; }
        IIssueModel Issue { get; set; }
        // Associated Objects
        // <None>
    }
}

namespace ComicVine.API.Interfaces.SearchModels
{
    public interface IConceptIssueSearchModel : IEntitySearchModel
    {
        int? ConceptId { get; set; }
        string ConceptCustomKey { get; set; }
        string ConceptApiDetailUrl { get; set; }
        string ConceptSiteDetailUrl { get; set; }
        string ConceptName { get; set; }
        string ConceptShortDescription { get; set; }
        string ConceptDescription { get; set; }
        int? IssueId { get; set; }
        string IssueCustomKey { get; set; }
        string IssueApiDetailUrl { get; set; }
        string IssueSiteDetailUrl { get; set; }
        string IssueName { get; set; }
        string IssueShortDescription { get; set; }
        string IssueDescription { get; set; }
    }
}

namespace ComicVine.API.Interfaces.Mappers
{
    public interface IConceptIssueMapper
        : IMapper<
            DataModels.IConceptIssue,
            Models.IConceptIssueModel,
            SearchModels.IConceptIssueSearchModel>
    {
    }
}

namespace ComicVine.API.Interfaces.Repositories
{
    public interface IConceptIssuesRepository
        : IRepositoryBase
        , IRepository<DataModels.IConceptIssue, SearchModels.IConceptIssueSearchModel>
    {
    }
}

namespace ComicVine.API.Interfaces.BusinessWorkflows
{
    public interface IConceptIssuesBusinessWorkflow
        : IBusinessWorkflow<Models.IConceptIssueModel, SearchModels.IConceptIssueSearchModel>
    {
    }
}
