// <auto-generated>
// <copyright file="Teams.TeamIssueRepositoryTests.cs" company="jothay.com">
// Copyright (c) 2015 Jothay Tech, Inc. All rights reserved.
// </copyright>
// <summary>Declares the TeamIssuesRepositoryTests class.</summary>
// <remarks>This file was auto-generated using RepositoryTestingFileMaster.tt in
// ComicVineScraper.API.Repositories.Testing\CodeGenerator</remarks>
// </auto-generated>
namespace ComicVineScraper.API.Testing.Repositories.Teams
{
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using API.Repositories;
    using DataModel.Schema;
    using Interfaces.SearchModels;
    using Moq;
    using SearchModels;
    using Xunit;

    public static class TeamIssuesMockingSetup
    {
        public static Mock<DataModel.ModelEntities> DoMockingSetupForContext(bool includeTeamIssuesData, out Mock<IDbSet<TeamIssue>> mockSetTeamIssues, bool markATeamIssueInactive = false)
        {
            var createDate = new System.DateTime(2015, 05, 28, 10, 45, 00);
            var mockContext = new Mock<DataModel.ModelEntities>();
            // Apply Data and set up IQueryable
            mockSetTeamIssues = new Mock<IDbSet<TeamIssue>>();
            var personData = (!includeTeamIssuesData ? new List<TeamIssue>() : new List<TeamIssue>
            {
                new TeamIssue { Id = 1, Active = !markATeamIssueInactive, CreatedDate = createDate, CustomKey = "KING-STEPHEN", ApiDetailUrl = "/TEST/KING-STEPHEN", },
                new TeamIssue { Id = 2, Active = true, CreatedDate = createDate.AddDays(1), CustomKey = "NIVEN-LARRY", ApiDetailUrl = "/TEST/NIVEN-LARRY", }
            }).AsQueryable();
            mockSetTeamIssues.As<IQueryable<TeamIssue>>().Setup(m => m.Provider).Returns(personData.Provider);
            mockSetTeamIssues.As<IQueryable<TeamIssue>>().Setup(m => m.Expression).Returns(personData.Expression);
            mockSetTeamIssues.As<IQueryable<TeamIssue>>().Setup(m => m.ElementType).Returns(personData.ElementType);
            mockSetTeamIssues.As<IQueryable<TeamIssue>>().Setup(m => m.GetEnumerator()).Returns(personData.GetEnumerator());
            mockContext.Setup(m => m.TeamIssues).Returns(mockSetTeamIssues.Object);
            mockContext.Setup(m => m.SetModified(It.IsAny<object>())).Callback(() => { });
            // Return
            return mockContext;
        }
    }

    public class TeamIssuesRepositoryTests
    {
        [Fact][Trait("Category", "TeamIssues")]
        public void Verify_Add_Should_AddTheEntityToTheContext()
        {
            // Arrange
            Mock<IDbSet<TeamIssue>> mockSetTeamIssues;
            var mockContext = TeamIssuesMockingSetup.DoMockingSetupForContext(false, out mockSetTeamIssues);
            var repository = new TeamIssuesRepository(mockContext.Object);
            var teamIssues = new TeamIssue { Active = true, CustomKey = "SALVATORE-RAA", };
            // Act
            repository.Add(teamIssues);
            // Assert
            mockSetTeamIssues.Verify(x => x.Add(teamIssues), Times.Once);
        }

        [Fact][Trait("Category", "TeamIssues")]
        public void Verify_Remove_Should_RemoveTheEntityFromTheContext()
        {
            // Arrange
            Mock<IDbSet<TeamIssue>> mockSetTeamIssues;
            var mockContext = TeamIssuesMockingSetup.DoMockingSetupForContext(true, out mockSetTeamIssues);
            var repository = new TeamIssuesRepository(mockContext.Object);
            var teamIssues = repository.Get(1);
            // Act
            repository.Remove(teamIssues);
            // Assert
            mockSetTeamIssues.Verify(x => x.Remove((TeamIssue)teamIssues), Times.Once);
        }

        [Fact][Trait("Category", "TeamIssues")]
        public void Verify_Deactivate_Should_SetTheActivePropertyToFalseOnTheEntity()
        {
            // Arrange
            Mock<IDbSet<TeamIssue>> mockSetTeamIssues;
            var mockContext = TeamIssuesMockingSetup.DoMockingSetupForContext(true, out mockSetTeamIssues);
            var repository = new TeamIssuesRepository(mockContext.Object);
            var teamIssues = repository.Get(1);
            // Act
            repository.Deactivate(teamIssues);
            // Assert
            Assert.Equal(false, teamIssues.Active);
        }

        [Fact][Trait("Category", "TeamIssues")]
        public void Verify_Update_Should_SetTheEntityStateToModified()
        {
            // Arrange
            Mock<IDbSet<TeamIssue>> mockSetTeamIssues;
            var mockContext = TeamIssuesMockingSetup.DoMockingSetupForContext(true, out mockSetTeamIssues);
            var repository = new TeamIssuesRepository(mockContext.Object);
            var teamIssues = repository.Get(1);
            teamIssues.ApiDetailUrl = "/TEST";
            // Act
            repository.Update(teamIssues);
            // Assert
            mockContext.Verify(x => x.SetModified(It.IsAny<object>()), Times.Once);
        }

        [Fact][Trait("Category", "TeamIssues")]
        public void Verify_Get_ByID_Should_ReturnTheCorrectTeamIssue()
        {
            // Arrange
            Mock<IDbSet<TeamIssue>> mockSetTeamIssues;
            var mockContext = TeamIssuesMockingSetup.DoMockingSetupForContext(true, out mockSetTeamIssues);
            var repository = new TeamIssuesRepository(mockContext.Object);
            // Act
            var teamIssues = repository.Get(1);
            // Assert
                        Assert.Equal("/TEST/KING-STEPHEN", teamIssues.ApiDetailUrl);
        }

        [Fact][Trait("Category", "TeamIssues")]
        public void Verify_Get_ByKey_Should_ReturnTheCorrectTeamIssue()
        {
            // Arrange
            Mock<IDbSet<TeamIssue>> mockSetTeamIssues;
            var mockContext = TeamIssuesMockingSetup.DoMockingSetupForContext(true, out mockSetTeamIssues);
            var repository = new TeamIssuesRepository(mockContext.Object);
            // Act
            var teamIssues = repository.Get("KING-STEPHEN");
            // Assert
                        Assert.Equal("/TEST/KING-STEPHEN", teamIssues.ApiDetailUrl);
        }

        [Fact][Trait("Category", "TeamIssues")]
        public void Verify_List_Should_ReturnAListOfTeamIssuesWithData()
        {
            // Arrange
            Mock<IDbSet<TeamIssue>> mockSetTeamIssues;
            var mockContext = TeamIssuesMockingSetup.DoMockingSetupForContext(true, out mockSetTeamIssues);
            var repository = new TeamIssuesRepository(mockContext.Object);
            // Act
            var teamIssues = repository.List.ToArray();
            // Assert
            Assert.Equal(2, teamIssues.Length);
            Assert.Equal(1, teamIssues[0].Id);
            Assert.Equal("/TEST/KING-STEPHEN", teamIssues[0].ApiDetailUrl);
            Assert.Equal(2, teamIssues[1].Id);
            Assert.Equal("/TEST/NIVEN-LARRY", teamIssues[1].ApiDetailUrl);
        }

        [Fact][Trait("Category", "TeamIssues")]
        public void Verify_Search_Should_ReturnAListOfTeamIssuesWithDataMatchingSearchParameters()
        {
            // Arrange
            Mock<IDbSet<TeamIssue>> mockSetTeamIssues;
            var mockContext = TeamIssuesMockingSetup.DoMockingSetupForContext(true, out mockSetTeamIssues, true);
            var repository = new TeamIssuesRepository(mockContext.Object);
            var searchModel = new Mock<ITeamIssueSearchModel>();
            // Act
            var teamIssues = repository.Search(searchModel.Object).ToArray();
            // Assert
            Assert.Equal(1, teamIssues.Length);
            Assert.Equal(2, teamIssues[0].Id);
            Assert.Equal("/TEST/NIVEN-LARRY", teamIssues[0].ApiDetailUrl);
            // Stephen King was filtered out because he was Inactive
        }

        [Fact][Trait("Category", "TeamIssues")]
        public void Verify_Search_WithSelectStatement_Should_ReturnAListOfDynamicObjects()
        {
            // Arrange
            Mock<IDbSet<TeamIssue>> mockSetTeamIssues;
            var mockContext = TeamIssuesMockingSetup.DoMockingSetupForContext(true, out mockSetTeamIssues, true);
            var repository = new TeamIssuesRepository(mockContext.Object);
            var searchModel = new Mock<ITeamIssueSearchModel>();
            // Act
            var teamIssues = repository.Search(searchModel.Object, i => new { i.Id, MyApiDetailUrl = i.ApiDetailUrl }).ToArray();
            // Assert
            Assert.Equal(1, teamIssues.Length);
            Assert.Equal(2, teamIssues[0].Id);
            Assert.Equal("/TEST/NIVEN-LARRY", teamIssues[0].MyApiDetailUrl);
            // Stephen King was filtered out because he was Inactive
        }

        [Fact][Trait("Category", "TeamIssues")]
        public void Verify_Search_WithModifiedSince_Should_ReturnAListOfTeamIssuesWithDataMatchingSearchParameters()
        {
            // Arrange
            Mock<IDbSet<TeamIssue>> mockSetTeamIssues;
            var mockContext = TeamIssuesMockingSetup.DoMockingSetupForContext(true, out mockSetTeamIssues, true);
            var repository = new TeamIssuesRepository(mockContext.Object);
            var createDate = new System.DateTime(2015, 05, 28, 10, 45, 00).AddDays(1).AddMinutes(-1);
            //var searchModel = new Mock<ITeamIssueSearchModel>();
            //searchModel.Setup(m => m.ModifiedSince).Returns(() => createDate);
            var searchModel = new TeamIssueSearchModel { ModifiedSince = createDate };
            // Act
            var teamIssues = repository.Search(searchModel/*.Object*/).ToArray();
            // Assert
            Assert.Equal(1, teamIssues.Length);
            Assert.Equal(2, teamIssues[0].Id);
            Assert.Equal("/TEST/NIVEN-LARRY", teamIssues[0].ApiDetailUrl);
            // Stephen King was filtered out because he was created before the modified since date
        }

        [Fact][Trait("Category", "TeamIssues")]
        public void Verify_Search_WithPaging_Should_ReturnAListOfTeamIssuesWithDataMatchingSearchParameters()
        {
            // Arrange
            Mock<IDbSet<TeamIssue>> mockSetTeamIssues;
            var mockContext = TeamIssuesMockingSetup.DoMockingSetupForContext(true, out mockSetTeamIssues);
            var repository = new TeamIssuesRepository(mockContext.Object);
            var searchModel = new TeamIssueSearchModel { Paging = new Paging { Skip = 1, Take = 1 } };
            // Act
            var teamIssues = repository.Search(searchModel/*.Object*/).ToArray();
            // Assert
            Assert.Equal(1, teamIssues.Length);
            Assert.Equal(2, teamIssues[0].Id);
            Assert.Equal("/TEST/NIVEN-LARRY", teamIssues[0].ApiDetailUrl);
            // Stephen King was filtered out because he was Skipped
        }
    }
}
