// <auto-generated>
// <copyright file="Concepts.IConceptMovieModel.cs" company="clarityventures.com">
// Copyright (c) 2015 Clarity Ventures, Inc. All rights reserved.
// </copyright>
// <summary>Implements the ConceptMovie model interfaces.</summary>
// <remarks>This file was autogenerated using InterfaceFileMaster.tt in ComicVine.API\Interfaces\00.AutoGenerated</remarks>
// </auto-generated>
namespace ComicVine.API.Interfaces.DataModels
{
    using System;
    using System.Collections.Generic;

    public interface IConceptMovie : IEntity
    {
        // ConceptMovie Properties
        // <None>
        // Related Objects
        int ConceptId { get; set; }
        IConcept Concept { get; set; }
        int MovieId { get; set; }
        IMovie Movie { get; set; }
        // Associated Objects
        // <None>
    }
}

namespace ComicVine.API.Interfaces.Models
{
    using System;
    using System.Collections.Generic;

    public interface IConceptMovieModel : IEntityModel
    {
        // ConceptMovie Properties
        // <None>
        // Related Objects
        int ConceptId { get; set; }
        IConceptModel Concept { get; set; }
        int MovieId { get; set; }
        IMovieModel Movie { get; set; }
        // Associated Objects
        // <None>
    }
}

namespace ComicVine.API.Interfaces.SearchModels
{
    public interface IConceptMovieSearchModel : IEntitySearchModel
    {
        int? ConceptId { get; set; }
        string ConceptCustomKey { get; set; }
        string ConceptApiDetailUrl { get; set; }
        string ConceptSiteDetailUrl { get; set; }
        string ConceptName { get; set; }
        string ConceptShortDescription { get; set; }
        string ConceptDescription { get; set; }
        int? MovieId { get; set; }
        string MovieCustomKey { get; set; }
        string MovieApiDetailUrl { get; set; }
        string MovieSiteDetailUrl { get; set; }
        string MovieName { get; set; }
        string MovieShortDescription { get; set; }
        string MovieDescription { get; set; }
    }
}

namespace ComicVine.API.Interfaces.Mappers
{
    public interface IConceptMovieMapper
        : IMapper<
            DataModels.IConceptMovie,
            Models.IConceptMovieModel,
            SearchModels.IConceptMovieSearchModel>
    {
    }
}

namespace ComicVine.API.Interfaces.Repositories
{
    public interface IConceptMoviesRepository
        : IRepositoryBase
        , IRepository<DataModels.IConceptMovie, SearchModels.IConceptMovieSearchModel>
    {
    }
}

namespace ComicVine.API.Interfaces.BusinessWorkflows
{
    public interface IConceptMoviesBusinessWorkflow
        : IBusinessWorkflow<Models.IConceptMovieModel, SearchModels.IConceptMovieSearchModel>
    {
    }
}
