// <auto-generated>
// <copyright file="dbo.IMovieModel.cs" company="clarityventures.com">
// Copyright (c) 2015 Clarity Ventures, Inc. All rights reserved.
// </copyright>
// <summary>Implements the Movie model interfaces.</summary>
// <remarks>This file was autogenerated using InterfaceFileMaster.tt in ComicVine.API\Interfaces\00.AutoGenerated</remarks>
// </auto-generated>
namespace ComicVine.API.Interfaces.DataModels
{
    using System;
    using System.Collections.Generic;

    public interface IMovie : INameableEntity
    {
        // Movie Properties
        bool HasStaffReview { get; set; }
        string Distributor { get; set; }
        decimal? BoxOfficeRevenue { get; set; }
        decimal? TotalRevenue { get; set; }
        decimal? Budget { get; set; }
        decimal? Rating { get; set; }
        DateTime? ReleaseDate { get; set; }
        decimal? RunTime { get; set; }
        // Related Objects
        int? PrimaryImageFileId { get; set; }
        IImageFile PrimaryImageFile { get; set; }
        // Associated Objects
        ICollection<ICharacter> Characters { get; set; }
        ICollection<IConcept> Concepts { get; set; }
        ICollection<ILocation> LocationCredits { get; set; }
        ICollection<IObject> ObjectCredits { get; set; }
        ICollection<IProducer> ProducerCredits { get; set; }
        ICollection<IStudio> StudioCredits { get; set; }
        ICollection<ITeam> TeamCredits { get; set; }
        ICollection<IWriter> WriterCredits { get; set; }
    }
}

namespace ComicVine.API.Interfaces.Models
{
    using System;
    using System.Collections.Generic;

    public interface IMovieModel : INameableEntityModel
    {
        // Movie Properties
        bool HasStaffReview { get; set; }
        string Distributor { get; set; }
        decimal? BoxOfficeRevenue { get; set; }
        decimal? TotalRevenue { get; set; }
        decimal? Budget { get; set; }
        decimal? Rating { get; set; }
        DateTime? ReleaseDate { get; set; }
        decimal? RunTime { get; set; }
        // Related Objects
        int? PrimaryImageFileId { get; set; }
        IImageFileModel PrimaryImageFile { get; set; }
        // Associated Objects
        List<ICharacterModel> Characters { get; set; }
        List<IConceptModel> Concepts { get; set; }
        List<ILocationModel> LocationCredits { get; set; }
        List<IObjectModel> ObjectCredits { get; set; }
        List<IProducerModel> ProducerCredits { get; set; }
        List<IStudioModel> StudioCredits { get; set; }
        List<ITeamModel> TeamCredits { get; set; }
        List<IWriterModel> WriterCredits { get; set; }
    }
}

namespace ComicVine.API.Interfaces.SearchModels
{
    public interface IMovieSearchModel : INameableEntitySearchModel
    {
        int? PrimaryImageFileId { get; set; }
        string PrimaryImageFileCustomKey { get; set; }
        string PrimaryImageFileApiDetailUrl { get; set; }
        string PrimaryImageFileSiteDetailUrl { get; set; }
        string PrimaryImageFileName { get; set; }
        string PrimaryImageFileShortDescription { get; set; }
        string PrimaryImageFileDescription { get; set; }
        bool? HasStaffReview { get; set; }
        string Distributor { get; set; }
    }
}

namespace ComicVine.API.Interfaces.Mappers
{
    public interface IMovieMapper
        : IMapper<
            DataModels.IMovie,
            Models.IMovieModel,
            SearchModels.IMovieSearchModel>
    {
    }
}

namespace ComicVine.API.Interfaces.Repositories
{
    public interface IMoviesRepository
        : IRepositoryBase
        , IRepository<DataModels.IMovie, SearchModels.IMovieSearchModel>
    {
    }
}

namespace ComicVine.API.Interfaces.BusinessWorkflows
{
    public interface IMoviesBusinessWorkflow
        : IBusinessWorkflow<Models.IMovieModel, SearchModels.IMovieSearchModel>
    {
    }
}
