// <auto-generated>
// <copyright file="Episodes.IEpisodeTeamFirstAppearanceModel.cs" company="clarityventures.com">
// Copyright (c) 2015 Clarity Ventures, Inc. All rights reserved.
// </copyright>
// <summary>Implements the EpisodeTeamFirstAppearance model interfaces.</summary>
// <remarks>This file was autogenerated using InterfaceFileMaster.tt in ComicVine.API\Interfaces\00.AutoGenerated</remarks>
// </auto-generated>
namespace ComicVine.API.Interfaces.DataModels
{
    using System;
    using System.Collections.Generic;

    public interface IEpisodeTeamFirstAppearance : IEntity
    {
        // EpisodeTeamFirstAppearance Properties
        // <None>
        // Related Objects
        int EpisodeId { get; set; }
        IEpisode Episode { get; set; }
        int TeamId { get; set; }
        ITeam Team { get; set; }
        // Associated Objects
        // <None>
    }
}

namespace ComicVine.API.Interfaces.Models
{
    using System;
    using System.Collections.Generic;

    public interface IEpisodeTeamFirstAppearanceModel : IEntityModel
    {
        // EpisodeTeamFirstAppearance Properties
        // <None>
        // Related Objects
        int EpisodeId { get; set; }
        IEpisodeModel Episode { get; set; }
        int TeamId { get; set; }
        ITeamModel Team { get; set; }
        // Associated Objects
        // <None>
    }
}

namespace ComicVine.API.Interfaces.SearchModels
{
    public interface IEpisodeTeamFirstAppearanceSearchModel : IEntitySearchModel
    {
        int? EpisodeId { get; set; }
        string EpisodeCustomKey { get; set; }
        string EpisodeApiDetailUrl { get; set; }
        string EpisodeSiteDetailUrl { get; set; }
        string EpisodeName { get; set; }
        string EpisodeShortDescription { get; set; }
        string EpisodeDescription { get; set; }
        int? TeamId { get; set; }
        string TeamCustomKey { get; set; }
        string TeamApiDetailUrl { get; set; }
        string TeamSiteDetailUrl { get; set; }
        string TeamName { get; set; }
        string TeamShortDescription { get; set; }
        string TeamDescription { get; set; }
    }
}

namespace ComicVine.API.Interfaces.Mappers
{
    public interface IEpisodeTeamFirstAppearanceMapper
        : IMapper<
            DataModels.IEpisodeTeamFirstAppearance,
            Models.IEpisodeTeamFirstAppearanceModel,
            SearchModels.IEpisodeTeamFirstAppearanceSearchModel>
    {
    }
}

namespace ComicVine.API.Interfaces.Repositories
{
    public interface IEpisodeTeamFirstAppearancesRepository
        : IRepositoryBase
        , IRepository<DataModels.IEpisodeTeamFirstAppearance, SearchModels.IEpisodeTeamFirstAppearanceSearchModel>
    {
    }
}

namespace ComicVine.API.Interfaces.BusinessWorkflows
{
    public interface IEpisodeTeamFirstAppearancesBusinessWorkflow
        : IBusinessWorkflow<Models.IEpisodeTeamFirstAppearanceModel, SearchModels.IEpisodeTeamFirstAppearanceSearchModel>
    {
    }
}
