// <auto-generated>
// <copyright file="Episodes.IEpisodeCharacterDiedModel.cs" company="clarityventures.com">
// Copyright (c) 2015 Clarity Ventures, Inc. All rights reserved.
// </copyright>
// <summary>Implements the EpisodeCharacterDied model interfaces.</summary>
// <remarks>This file was autogenerated using InterfaceFileMaster.tt in ComicVine.API\Interfaces\00.AutoGenerated</remarks>
// </auto-generated>
namespace ComicVine.API.Interfaces.DataModels
{
    using System;
    using System.Collections.Generic;

    public interface IEpisodeCharacterDied : IEntity
    {
        // EpisodeCharacterDied Properties
        // <None>
        // Related Objects
        int EpisodeId { get; set; }
        IEpisode Episode { get; set; }
        int CharacterId { get; set; }
        ICharacter Character { get; set; }
        // Associated Objects
        // <None>
    }
}

namespace ComicVine.API.Interfaces.Models
{
    using System;
    using System.Collections.Generic;

    public interface IEpisodeCharacterDiedModel : IEntityModel
    {
        // EpisodeCharacterDied Properties
        // <None>
        // Related Objects
        int EpisodeId { get; set; }
        IEpisodeModel Episode { get; set; }
        int CharacterId { get; set; }
        ICharacterModel Character { get; set; }
        // Associated Objects
        // <None>
    }
}

namespace ComicVine.API.Interfaces.SearchModels
{
    public interface IEpisodeCharacterDiedSearchModel : IEntitySearchModel
    {
        int? EpisodeId { get; set; }
        string EpisodeCustomKey { get; set; }
        string EpisodeApiDetailUrl { get; set; }
        string EpisodeSiteDetailUrl { get; set; }
        string EpisodeName { get; set; }
        string EpisodeShortDescription { get; set; }
        string EpisodeDescription { get; set; }
        int? CharacterId { get; set; }
        string CharacterCustomKey { get; set; }
        string CharacterApiDetailUrl { get; set; }
        string CharacterSiteDetailUrl { get; set; }
        string CharacterName { get; set; }
        string CharacterShortDescription { get; set; }
        string CharacterDescription { get; set; }
    }
}

namespace ComicVine.API.Interfaces.Mappers
{
    public interface IEpisodeCharacterDiedMapper
        : IMapper<
            DataModels.IEpisodeCharacterDied,
            Models.IEpisodeCharacterDiedModel,
            SearchModels.IEpisodeCharacterDiedSearchModel>
    {
    }
}

namespace ComicVine.API.Interfaces.Repositories
{
    public interface IEpisodeCharactersDiedRepository
        : IRepositoryBase
        , IRepository<DataModels.IEpisodeCharacterDied, SearchModels.IEpisodeCharacterDiedSearchModel>
    {
    }
}

namespace ComicVine.API.Interfaces.BusinessWorkflows
{
    public interface IEpisodeCharactersDiedBusinessWorkflow
        : IBusinessWorkflow<Models.IEpisodeCharacterDiedModel, SearchModels.IEpisodeCharacterDiedSearchModel>
    {
    }
}
