// <auto-generated>
// <copyright file="StoryArcs.IStoryArcIssueModel.cs" company="clarityventures.com">
// Copyright (c) 2015 Clarity Ventures, Inc. All rights reserved.
// </copyright>
// <summary>Implements the StoryArcIssue model interfaces.</summary>
// <remarks>This file was autogenerated using InterfaceFileMaster.tt in ComicVine.API\Interfaces\00.AutoGenerated</remarks>
// </auto-generated>
namespace ComicVine.API.Interfaces.DataModels
{
    using System;
    using System.Collections.Generic;

    public interface IStoryArcIssue : IEntity
    {
        // StoryArcIssue Properties
        // <None>
        // Related Objects
        int StoryArcId { get; set; }
        IStoryArc StoryArc { get; set; }
        int IssueId { get; set; }
        IIssue Issue { get; set; }
        // Associated Objects
        // <None>
    }
}

namespace ComicVine.API.Interfaces.Models
{
    using System;
    using System.Collections.Generic;

    public interface IStoryArcIssueModel : IEntityModel
    {
        // StoryArcIssue Properties
        // <None>
        // Related Objects
        int StoryArcId { get; set; }
        IStoryArcModel StoryArc { get; set; }
        int IssueId { get; set; }
        IIssueModel Issue { get; set; }
        // Associated Objects
        // <None>
    }
}

namespace ComicVine.API.Interfaces.SearchModels
{
    public interface IStoryArcIssueSearchModel : IEntitySearchModel
    {
        int? StoryArcId { get; set; }
        string StoryArcCustomKey { get; set; }
        string StoryArcApiDetailUrl { get; set; }
        string StoryArcSiteDetailUrl { get; set; }
        string StoryArcName { get; set; }
        string StoryArcShortDescription { get; set; }
        string StoryArcDescription { get; set; }
        int? IssueId { get; set; }
        string IssueCustomKey { get; set; }
        string IssueApiDetailUrl { get; set; }
        string IssueSiteDetailUrl { get; set; }
        string IssueName { get; set; }
        string IssueShortDescription { get; set; }
        string IssueDescription { get; set; }
    }
}

namespace ComicVine.API.Interfaces.Mappers
{
    public interface IStoryArcIssueMapper
        : IMapper<
            DataModels.IStoryArcIssue,
            Models.IStoryArcIssueModel,
            SearchModels.IStoryArcIssueSearchModel>
    {
    }
}

namespace ComicVine.API.Interfaces.Repositories
{
    public interface IStoryArcIssuesRepository
        : IRepositoryBase
        , IRepository<DataModels.IStoryArcIssue, SearchModels.IStoryArcIssueSearchModel>
    {
    }
}

namespace ComicVine.API.Interfaces.BusinessWorkflows
{
    public interface IStoryArcIssuesBusinessWorkflow
        : IBusinessWorkflow<Models.IStoryArcIssueModel, SearchModels.IStoryArcIssueSearchModel>
    {
    }
}
