// <auto-generated>
// <copyright file="Episodes.IEpisodeMappings.cs" company="jothay.com">
// Copyright (c) 2015 Jothay Tech, Inc. All rights reserved.
// </copyright>
// <summary>Implements the Mapping Layer functions between Episode and EpisodeModel.</summary>
// <remarks>This file was auto-generated using MappingFileMaster.tt in
// ComicVineScraper.API.Mappings\CodeGenerator</remarks>
// </auto-generated>
// ReSharper disable ClassWithVirtualMembersNeverInherited.Global, RedundantUsingDirective, UnusedMember.Global, UnusedMethodReturnValue.Global
namespace ComicVineScraper.API.Mappings//.Episodes
{
    using System.Collections.Generic;
    using System.Linq;
    using DataModel.Schema;
    using Interfaces.DataModels;
    using Interfaces.Mappers;
    using Interfaces.Models;
    using Interfaces.SearchModels;
    using Models;
    using SearchModels;

    public static class EpisodeMapperExtensions
    {
        public static IEpisodeMapper Mapper = new EpisodeMapper();

        public static void OverrideMapper(IEpisodeMapper mapper) { Mapper = mapper; }

        public static IEpisode MapToEntity(this IEpisodeModel model, int currentDepth = 1)
        {
            return Mapper.MapToEntity(model, currentDepth);
        }
        public static void MapToEntity(this IEpisodeModel model, ref IEpisode entity, int currentDepth = 1)
        {
            Mapper.MapToEntity(model, ref entity, currentDepth);
        }
        public static IEpisodeModel MapToModel(this IEpisode entity, int currentDepth = 1)
        {
            return Mapper.MapToModel(entity, currentDepth);
        }
        public static IEpisodeModel MapToModelLite(this IEpisode entity, int currentDepth = 1)
        {
            return Mapper.MapToModelLite(entity, currentDepth);
        }
        public static IEpisodeModel MapToModelListing(this IEpisode entity, int currentDepth = 1)
        {
            return Mapper.MapToModelListing(entity, currentDepth);
        }
        public static IEpisodeSearchModel MapToSearchModel(this IEpisodeModel model)
        {
            return Mapper.MapToSearchModel(model);
        }
        public static bool AreEqual(this IEpisodeModel model, IEpisode entity)
        {
            return Mapper.AreEqual(model, entity);
        }
    }

    public class EpisodeMapper : IEpisodeMapper
    {
        public virtual IEpisode MapToEntity(IEpisodeModel model, int currentDepth = 1)
        {
            currentDepth++;
            var entity = NameableEntityMapper.MapToEntity<Episode, IEpisodeModel>(model);
            // Episode Properties
            entity.HasStaffReview = model.HasStaffReview;
            entity.AirDate = model.AirDate;
            entity.EpisodeCode = model.EpisodeCode;
            entity.SeasonNumber = model.SeasonNumber;
            entity.EpisodeNumber = model.EpisodeNumber;
            // Related Objects
            entity.PrimaryImageFileId = model.PrimaryImageFileId;
            entity.PrimaryImageFile = (ImageFile)model.PrimaryImageFile?.MapToEntity();
            entity.SeriesId = model.SeriesId;
            entity.Series = (Series)model.Series?.MapToEntity();
            // Associated Objects
            entity.EpisodeAliases = model.EpisodeAliases?.Where(i => i.Active).Select(EpisodeAliasMapperExtensions.MapToEntity).Cast<EpisodeAlias>().ToList();
            entity.EpisodeCharacters = model.EpisodeCharacters?.Where(i => i.Active).Select(EpisodeCharacterMapperExtensions.MapToEntity).Cast<EpisodeCharacter>().ToList();
            entity.EpisodeCharactersDied = model.EpisodeCharactersDied?.Where(i => i.Active).Select(EpisodeCharacterDiedMapperExtensions.MapToEntity).Cast<EpisodeCharacterDied>().ToList();
            entity.EpisodeCharacterFirstAppearances = model.EpisodeCharacterFirstAppearances?.Where(i => i.Active).Select(EpisodeCharacterFirstAppearanceMapperExtensions.MapToEntity).Cast<EpisodeCharacterFirstAppearance>().ToList();
            entity.EpisodeConcepts = model.EpisodeConcepts?.Where(i => i.Active).Select(EpisodeConceptMapperExtensions.MapToEntity).Cast<EpisodeConcept>().ToList();
            entity.EpisodeConceptFirstAppearances = model.EpisodeConceptFirstAppearances?.Where(i => i.Active).Select(EpisodeConceptFirstAppearanceMapperExtensions.MapToEntity).Cast<EpisodeConceptFirstAppearance>().ToList();
            entity.EpisodeLocations = model.EpisodeLocations?.Where(i => i.Active).Select(EpisodeLocationMapperExtensions.MapToEntity).Cast<EpisodeLocation>().ToList();
            entity.EpisodeLocationFirstAppearances = model.EpisodeLocationFirstAppearances?.Where(i => i.Active).Select(EpisodeLocationFirstAppearanceMapperExtensions.MapToEntity).Cast<EpisodeLocationFirstAppearance>().ToList();
            entity.EpisodeObjects = model.EpisodeObjects?.Where(i => i.Active).Select(EpisodeObjectMapperExtensions.MapToEntity).Cast<EpisodeObject>().ToList();
            entity.EpisodeObjectFirstAppearances = model.EpisodeObjectFirstAppearances?.Where(i => i.Active).Select(EpisodeObjectFirstAppearanceMapperExtensions.MapToEntity).Cast<EpisodeObjectFirstAppearance>().ToList();
            entity.EpisodePeople = model.EpisodePeople?.Where(i => i.Active).Select(EpisodePersonMapperExtensions.MapToEntity).Cast<EpisodePerson>().ToList();
            entity.EpisodeStoryArcs = model.EpisodeStoryArcs?.Where(i => i.Active).Select(EpisodeStoryArcMapperExtensions.MapToEntity).Cast<EpisodeStoryArc>().ToList();
            entity.EpisodeStoryArcFirstAppearances = model.EpisodeStoryArcFirstAppearances?.Where(i => i.Active).Select(EpisodeStoryArcFirstAppearanceMapperExtensions.MapToEntity).Cast<EpisodeStoryArcFirstAppearance>().ToList();
            entity.EpisodeTeams = model.EpisodeTeams?.Where(i => i.Active).Select(EpisodeTeamMapperExtensions.MapToEntity).Cast<EpisodeTeam>().ToList();
            entity.EpisodeTeamFirstAppearances = model.EpisodeTeamFirstAppearances?.Where(i => i.Active).Select(EpisodeTeamFirstAppearanceMapperExtensions.MapToEntity).Cast<EpisodeTeamFirstAppearance>().ToList();
            // Return Entity
            return entity;
        }

        public virtual void MapToEntity(IEpisodeModel model, ref IEpisode entity, int currentDepth = 1)
        {
            currentDepth++;
            // Assign Base properties
            NameableEntityMapper.MapToEntity(model, ref entity);
            // Episode Properties
            entity.HasStaffReview = model.HasStaffReview;
            entity.AirDate = model.AirDate;
            entity.EpisodeCode = model.EpisodeCode;
            entity.SeasonNumber = model.SeasonNumber;
            entity.EpisodeNumber = model.EpisodeNumber;
            // Related Objects
            entity.PrimaryImageFileId = model.PrimaryImageFileId;
            entity.PrimaryImageFile = (ImageFile)model.PrimaryImageFile?.MapToEntity();
            entity.SeriesId = model.SeriesId;
            entity.Series = (Series)model.Series?.MapToEntity();
            // Associated Objects
            entity.EpisodeAliases = model.EpisodeAliases?.Where(i => i.Active).Select(EpisodeAliasMapperExtensions.MapToEntity).ToList();
            entity.EpisodeCharacters = model.EpisodeCharacters?.Where(i => i.Active).Select(EpisodeCharacterMapperExtensions.MapToEntity).ToList();
            entity.EpisodeCharactersDied = model.EpisodeCharactersDied?.Where(i => i.Active).Select(EpisodeCharacterDiedMapperExtensions.MapToEntity).ToList();
            entity.EpisodeCharacterFirstAppearances = model.EpisodeCharacterFirstAppearances?.Where(i => i.Active).Select(EpisodeCharacterFirstAppearanceMapperExtensions.MapToEntity).ToList();
            entity.EpisodeConcepts = model.EpisodeConcepts?.Where(i => i.Active).Select(EpisodeConceptMapperExtensions.MapToEntity).ToList();
            entity.EpisodeConceptFirstAppearances = model.EpisodeConceptFirstAppearances?.Where(i => i.Active).Select(EpisodeConceptFirstAppearanceMapperExtensions.MapToEntity).ToList();
            entity.EpisodeLocations = model.EpisodeLocations?.Where(i => i.Active).Select(EpisodeLocationMapperExtensions.MapToEntity).ToList();
            entity.EpisodeLocationFirstAppearances = model.EpisodeLocationFirstAppearances?.Where(i => i.Active).Select(EpisodeLocationFirstAppearanceMapperExtensions.MapToEntity).ToList();
            entity.EpisodeObjects = model.EpisodeObjects?.Where(i => i.Active).Select(EpisodeObjectMapperExtensions.MapToEntity).ToList();
            entity.EpisodeObjectFirstAppearances = model.EpisodeObjectFirstAppearances?.Where(i => i.Active).Select(EpisodeObjectFirstAppearanceMapperExtensions.MapToEntity).ToList();
            entity.EpisodePeople = model.EpisodePeople?.Where(i => i.Active).Select(EpisodePersonMapperExtensions.MapToEntity).ToList();
            entity.EpisodeStoryArcs = model.EpisodeStoryArcs?.Where(i => i.Active).Select(EpisodeStoryArcMapperExtensions.MapToEntity).ToList();
            entity.EpisodeStoryArcFirstAppearances = model.EpisodeStoryArcFirstAppearances?.Where(i => i.Active).Select(EpisodeStoryArcFirstAppearanceMapperExtensions.MapToEntity).ToList();
            entity.EpisodeTeams = model.EpisodeTeams?.Where(i => i.Active).Select(EpisodeTeamMapperExtensions.MapToEntity).ToList();
            entity.EpisodeTeamFirstAppearances = model.EpisodeTeamFirstAppearances?.Where(i => i.Active).Select(EpisodeTeamFirstAppearanceMapperExtensions.MapToEntity).ToList();
        }

        public virtual IEpisodeModel MapToModel(IEpisode entity, int currentDepth = 1)
        {
            currentDepth++;
            var model = NameableEntityMapper.MapToModel<IEpisode, EpisodeModel>(entity);
            // Episode Properties
            model.HasStaffReview = entity.HasStaffReview;
            model.AirDate = entity.AirDate;
            model.EpisodeCode = entity.EpisodeCode;
            model.SeasonNumber = entity.SeasonNumber;
            model.EpisodeNumber = entity.EpisodeNumber;
            // Related Objects
            model.PrimaryImageFileId = entity.PrimaryImageFileId;
            model.PrimaryImageFile = entity.PrimaryImageFile?.MapToModel();
            model.SeriesId = entity.SeriesId;
            model.Series = entity.Series?.MapToModel();
            // Associated Objects
            model.EpisodeAliases = entity.EpisodeAliases?.Where(i => i.Active).Select(EpisodeAliasMapperExtensions.MapToModelLite).ToList();
            model.EpisodeCharacters = entity.EpisodeCharacters?.Where(i => i.Active).Select(EpisodeCharacterMapperExtensions.MapToModelLite).ToList();
            model.EpisodeCharactersDied = entity.EpisodeCharactersDied?.Where(i => i.Active).Select(EpisodeCharacterDiedMapperExtensions.MapToModelLite).ToList();
            model.EpisodeCharacterFirstAppearances = entity.EpisodeCharacterFirstAppearances?.Where(i => i.Active).Select(EpisodeCharacterFirstAppearanceMapperExtensions.MapToModelLite).ToList();
            model.EpisodeConcepts = entity.EpisodeConcepts?.Where(i => i.Active).Select(EpisodeConceptMapperExtensions.MapToModelLite).ToList();
            model.EpisodeConceptFirstAppearances = entity.EpisodeConceptFirstAppearances?.Where(i => i.Active).Select(EpisodeConceptFirstAppearanceMapperExtensions.MapToModelLite).ToList();
            model.EpisodeLocations = entity.EpisodeLocations?.Where(i => i.Active).Select(EpisodeLocationMapperExtensions.MapToModelLite).ToList();
            model.EpisodeLocationFirstAppearances = entity.EpisodeLocationFirstAppearances?.Where(i => i.Active).Select(EpisodeLocationFirstAppearanceMapperExtensions.MapToModelLite).ToList();
            model.EpisodeObjects = entity.EpisodeObjects?.Where(i => i.Active).Select(EpisodeObjectMapperExtensions.MapToModelLite).ToList();
            model.EpisodeObjectFirstAppearances = entity.EpisodeObjectFirstAppearances?.Where(i => i.Active).Select(EpisodeObjectFirstAppearanceMapperExtensions.MapToModelLite).ToList();
            model.EpisodePeople = entity.EpisodePeople?.Where(i => i.Active).Select(EpisodePersonMapperExtensions.MapToModelLite).ToList();
            model.EpisodeStoryArcs = entity.EpisodeStoryArcs?.Where(i => i.Active).Select(EpisodeStoryArcMapperExtensions.MapToModelLite).ToList();
            model.EpisodeStoryArcFirstAppearances = entity.EpisodeStoryArcFirstAppearances?.Where(i => i.Active).Select(EpisodeStoryArcFirstAppearanceMapperExtensions.MapToModelLite).ToList();
            model.EpisodeTeams = entity.EpisodeTeams?.Where(i => i.Active).Select(EpisodeTeamMapperExtensions.MapToModelLite).ToList();
            model.EpisodeTeamFirstAppearances = entity.EpisodeTeamFirstAppearances?.Where(i => i.Active).Select(EpisodeTeamFirstAppearanceMapperExtensions.MapToModelLite).ToList();
            // Return Entity
            return model;
        }

        public virtual IEpisodeModel MapToModelLite(IEpisode entity, int currentDepth = 1)
        {
            currentDepth++;
            var model = NameableEntityMapper.MapToModelLite<IEpisode, EpisodeModel>(entity);
            // Episode Properties
            model.HasStaffReview = entity.HasStaffReview;
            model.AirDate = entity.AirDate;
            model.EpisodeCode = entity.EpisodeCode;
            model.SeasonNumber = entity.SeasonNumber;
            model.EpisodeNumber = entity.EpisodeNumber;
            // Related Objects
            model.PrimaryImageFileId = entity.PrimaryImageFileId;
            model.SeriesId = entity.SeriesId;
            // Return Entity
            return model;
        }

        public virtual IEpisodeModel MapToModelListing(IEpisode entity, int currentDepth = 1)
        {
            currentDepth++;
            var model = NameableEntityMapper.MapToModelListing<IEpisode, EpisodeModel>(entity);
            // Episode Properties
            model.HasStaffReview = entity.HasStaffReview;
            model.AirDate = entity.AirDate;
            model.EpisodeCode = entity.EpisodeCode;
            model.SeasonNumber = entity.SeasonNumber;
            model.EpisodeNumber = entity.EpisodeNumber;
            // Related Objects
            model.PrimaryImageFileId = entity.PrimaryImageFileId;
            model.SeriesId = entity.SeriesId;
            // Return Entity
            return model;
        }

        public virtual IEpisodeSearchModel MapToSearchModel(IEpisodeModel model)
        {
            var searchModel = NameableEntityMapper.MapToSearchModel<IEpisodeModel, EpisodeSearchModel>(model);
            // Search Properties
            searchModel.PrimaryImageFileId = model.PrimaryImageFileId;
            searchModel.PrimaryImageFileCustomKey = model.PrimaryImageFile?.CustomKey;
            searchModel.PrimaryImageFileApiDetailUrl = model.PrimaryImageFile?.ApiDetailUrl;
            searchModel.PrimaryImageFileSiteDetailUrl = model.PrimaryImageFile?.SiteDetailUrl;
            searchModel.PrimaryImageFileName = model.PrimaryImageFile?.Name;
            searchModel.PrimaryImageFileShortDescription = model.PrimaryImageFile?.ShortDescription;
            searchModel.PrimaryImageFileDescription = model.PrimaryImageFile?.Description;
            searchModel.SeriesId = model.SeriesId;
            searchModel.SeriesCustomKey = model.Series?.CustomKey;
            searchModel.SeriesApiDetailUrl = model.Series?.ApiDetailUrl;
            searchModel.SeriesSiteDetailUrl = model.Series?.SiteDetailUrl;
            searchModel.SeriesName = model.Series?.Name;
            searchModel.SeriesShortDescription = model.Series?.ShortDescription;
            searchModel.SeriesDescription = model.Series?.Description;
            searchModel.HasStaffReview = model.HasStaffReview;
            // Return Search Model
            return searchModel;
        }

        public virtual bool AreEqual(IEpisodeModel model, IEpisode entity)
        {
            return NameableEntityMapper.AreEqual(model, entity)
                // Episode Properties
                && model.HasStaffReview == entity.HasStaffReview
                && model.AirDate == entity.AirDate
                && model.EpisodeCode == entity.EpisodeCode
                && model.SeasonNumber == entity.SeasonNumber
                && model.EpisodeNumber == entity.EpisodeNumber
                // Related Objects
                && model.PrimaryImageFileId == entity.PrimaryImageFileId
                && model.SeriesId == entity.SeriesId
                ;
        }
    }
}
