// <auto-generated>
// <copyright file="Volumes.IVolumeTeamMappings.cs" company="jothay.com">
// Copyright (c) 2015 Jothay Tech, Inc. All rights reserved.
// </copyright>
// <summary>Implements the Mapping Layer functions between VolumeTeam and VolumeTeamModel.</summary>
// <remarks>This file was auto-generated using MappingFileMaster.tt in
// ComicVineScraper.API.Mappings\CodeGenerator</remarks>
// </auto-generated>
// ReSharper disable ClassWithVirtualMembersNeverInherited.Global, RedundantUsingDirective, UnusedMember.Global, UnusedMethodReturnValue.Global
namespace ComicVineScraper.API.Mappings//.Volumes
{
    using System.Collections.Generic;
    using System.Linq;
    using DataModel.Schema;
    using Interfaces.DataModels;
    using Interfaces.Mappers;
    using Interfaces.Models;
    using Interfaces.SearchModels;
    using Models;
    using SearchModels;

    public static class VolumeTeamMapperExtensions
    {
        public static IVolumeTeamMapper Mapper = new VolumeTeamMapper();

        public static void OverrideMapper(IVolumeTeamMapper mapper) { Mapper = mapper; }

        public static IVolumeTeam MapToEntity(this IVolumeTeamModel model, int currentDepth = 1)
        {
            return Mapper.MapToEntity(model, currentDepth);
        }
        public static void MapToEntity(this IVolumeTeamModel model, ref IVolumeTeam entity, int currentDepth = 1)
        {
            Mapper.MapToEntity(model, ref entity, currentDepth);
        }
        public static IVolumeTeamModel MapToModel(this IVolumeTeam entity, int currentDepth = 1)
        {
            return Mapper.MapToModel(entity, currentDepth);
        }
        public static IVolumeTeamModel MapToModelLite(this IVolumeTeam entity, int currentDepth = 1)
        {
            return Mapper.MapToModelLite(entity, currentDepth);
        }
        public static IVolumeTeamModel MapToModelListing(this IVolumeTeam entity, int currentDepth = 1)
        {
            return Mapper.MapToModelListing(entity, currentDepth);
        }
        public static IVolumeTeamSearchModel MapToSearchModel(this IVolumeTeamModel model)
        {
            return Mapper.MapToSearchModel(model);
        }
        public static bool AreEqual(this IVolumeTeamModel model, IVolumeTeam entity)
        {
            return Mapper.AreEqual(model, entity);
        }
    }

    public class VolumeTeamMapper : IVolumeTeamMapper
    {
        public virtual IVolumeTeam MapToEntity(IVolumeTeamModel model, int currentDepth = 1)
        {
            currentDepth++;
            var entity = EntityMapper.MapToEntity<VolumeTeam, IVolumeTeamModel>(model);
            // VolumeTeam Properties
            // <None>
            // Related Objects
            entity.VolumeId = model.VolumeId;
            entity.Volume = (Volume)model.Volume?.MapToEntity();
            entity.TeamId = model.TeamId;
            entity.Team = (Team)model.Team?.MapToEntity();
            // Associated Objects
            // <None>
            // Return Entity
            return entity;
        }

        public virtual void MapToEntity(IVolumeTeamModel model, ref IVolumeTeam entity, int currentDepth = 1)
        {
            currentDepth++;
            // Assign Base properties
            EntityMapper.MapToEntity(model, ref entity);
            // VolumeTeam Properties
            // <None>
            // Related Objects
            entity.VolumeId = model.VolumeId;
            entity.Volume = (Volume)model.Volume?.MapToEntity();
            entity.TeamId = model.TeamId;
            entity.Team = (Team)model.Team?.MapToEntity();
            // Associated Objects
            // <None>
        }

        public virtual IVolumeTeamModel MapToModel(IVolumeTeam entity, int currentDepth = 1)
        {
            currentDepth++;
            var model = EntityMapper.MapToModel<IVolumeTeam, VolumeTeamModel>(entity);
            // VolumeTeam Properties
            // <None>
            // Related Objects
            model.VolumeId = entity.VolumeId;
            model.Volume = entity.Volume?.MapToModel();
            model.TeamId = entity.TeamId;
            model.Team = entity.Team?.MapToModel();
            // Associated Objects
            // <None>
            // Return Entity
            return model;
        }

        public virtual IVolumeTeamModel MapToModelLite(IVolumeTeam entity, int currentDepth = 1)
        {
            currentDepth++;
            var model = EntityMapper.MapToModelLite<IVolumeTeam, VolumeTeamModel>(entity);
            // VolumeTeam Properties
            // <None>
            // Related Objects
            model.VolumeId = entity.VolumeId;
            model.TeamId = entity.TeamId;
            // Return Entity
            return model;
        }

        public virtual IVolumeTeamModel MapToModelListing(IVolumeTeam entity, int currentDepth = 1)
        {
            currentDepth++;
            var model = EntityMapper.MapToModelListing<IVolumeTeam, VolumeTeamModel>(entity);
            // VolumeTeam Properties
            // <None>
            // Related Objects
            model.VolumeId = entity.VolumeId;
            model.TeamId = entity.TeamId;
            // Return Entity
            return model;
        }

        public virtual IVolumeTeamSearchModel MapToSearchModel(IVolumeTeamModel model)
        {
            var searchModel = EntityMapper.MapToSearchModel<IVolumeTeamModel, VolumeTeamSearchModel>(model);
            // Search Properties
            searchModel.VolumeId = model.VolumeId;
            searchModel.VolumeCustomKey = model.Volume?.CustomKey;
            searchModel.VolumeApiDetailUrl = model.Volume?.ApiDetailUrl;
            searchModel.VolumeSiteDetailUrl = model.Volume?.SiteDetailUrl;
            searchModel.VolumeName = model.Volume?.Name;
            searchModel.VolumeShortDescription = model.Volume?.ShortDescription;
            searchModel.VolumeDescription = model.Volume?.Description;
            searchModel.TeamId = model.TeamId;
            searchModel.TeamCustomKey = model.Team?.CustomKey;
            searchModel.TeamApiDetailUrl = model.Team?.ApiDetailUrl;
            searchModel.TeamSiteDetailUrl = model.Team?.SiteDetailUrl;
            searchModel.TeamName = model.Team?.Name;
            searchModel.TeamShortDescription = model.Team?.ShortDescription;
            searchModel.TeamDescription = model.Team?.Description;
            // Return Search Model
            return searchModel;
        }

        public virtual bool AreEqual(IVolumeTeamModel model, IVolumeTeam entity)
        {
            return EntityMapper.AreEqual(model, entity)
                // VolumeTeam Properties
                // <None>
                // Related Objects
                && model.VolumeId == entity.VolumeId
                && model.TeamId == entity.TeamId
                ;
        }
    }
}
