// <auto-generated>
// <copyright file="Concepts.IConceptMovieRepository.cs" company="clarityventures.com">
// Copyright (c) 2015 Clarity Ventures, Inc. All rights reserved.
// </copyright>
// <summary>Implements the ConceptMoviesRepository Class.</summary>
// <remarks>This file was autogenerated using RepositoryFileMaster.tt in ComicVine.API.Repositories\Repositories\CodeGenerator</remarks>
// </auto-generated>
namespace ComicVine.API.Repositories//.Concepts
{
    using System.Collections.Generic;
    using System.Linq;
    using DataModel.Schema;
    using Interfaces.DataModels;
    using Interfaces.Repositories;
    using Interfaces.SearchModels;

    public class ConceptMoviesRepository : RepositoryBase, IConceptMoviesRepository
    {
        public ConceptMoviesRepository(object context) : base(context) { }

        public void Add(IConceptMovie entity)
        {
            Context.ConceptMovies.Add((ConceptMovie)entity);
        }

        public void Remove(IConceptMovie entity)
        {
            Context.ConceptMovies.Remove((ConceptMovie)entity);
        }

        public void Deactivate(IConceptMovie entity)
        {
            entity.Active = false;
            Update(entity);
        }

        public void Update(IConceptMovie entity)
        {
            Context.SetModified(entity);
        }

        public IConceptMovie Get(int id)
        {
            return Context.ConceptMovies.FirstOrDefault(r => r.Id == id);
        }

        public IConceptMovie Get(string key)
        {
            return Context.ConceptMovies.FirstOrDefault(r => r.CustomKey == key);
        }

        public IEnumerable<IConceptMovie> List => Context.ConceptMovies;

        public IEnumerable<dynamic> Search(IConceptMovieSearchModel searchModel, System.Func<IConceptMovie, dynamic> selectStatement, bool requireActive = true)
        {
            return SearchCommon(searchModel, requireActive)
                .Select(selectStatement);
        }

        public IEnumerable<IConceptMovie> Search(IConceptMovieSearchModel searchModel, bool requireActive = true)
        {
            return SearchCommon(searchModel, requireActive);
        }

        // ReSharper disable once ReturnTypeCanBeEnumerable.Local
        // ReSharper disable once SuggestBaseTypeForParameter
        private IQueryable<IConceptMovie> SearchCommon(IConceptMovieSearchModel searchModel, bool requireActive)
        {
            return Context.ConceptMovies
                .FilterByBaseFilters(searchModel, requireActive)
                .FilterByPaging(searchModel.Paging);
        }
    }

    public static partial class ConceptMovieSearchExtensions
    {
    } // end ConceptMovieSearchExtensions
}
