// <auto-generated>
// <copyright file="Volumes.IVolumeCharacterRepository.cs" company="clarityventures.com">
// Copyright (c) 2015 Clarity Ventures, Inc. All rights reserved.
// </copyright>
// <summary>Implements the VolumeCharactersRepository Class.</summary>
// <remarks>This file was autogenerated using RepositoryTestingFileMaster.tt in ComicVine.API.Repositories.Testing\Repositories\CodeGenerator</remarks>
// </auto-generated>
namespace ComicVine.API.Testing.Mappings.Volumes
{
    using System.Collections.Generic;
    using API.Models;
    using API.Mappings;
    using DataModel.Schema;
    using Interfaces.DataModels;
    using Interfaces.Models;
    using Moq;
    using Xunit;

    public static class VolumeCharactersMockingSetup
    {
        public static Mock<IVolumeCharacterModel> DoMockingSetupForVolumeCharacterModel(int idReturnValue = 0, string name = "Stephen King")
        {
            var mockVolumeCharacterModel = new Mock<IVolumeCharacterModel>();
            // Mock Functions
            mockVolumeCharacterModel.Setup(m => m.Id).Returns(() => idReturnValue);
            mockVolumeCharacterModel.Setup(m => m.Active).Returns(() => true);
            mockVolumeCharacterModel.Setup(m => m.CustomKey).Returns(() => "KING-STEPHEN");
            mockVolumeCharacterModel.Setup(m => m.ApiDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockVolumeCharacterModel.Setup(m => m.SiteDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockVolumeCharacterModel.Setup(m => m.CreatedDate).Returns(() => new System.DateTime(2015, 10, 1));
            mockVolumeCharacterModel.Setup(m => m.UpdatedDate).Returns(() => null);
            //mockVolumeCharacterModel.Setup(m => m.Name).Returns(() => name);
            //mockVolumeCharacterModel.Setup(m => m.ShortDescription).Returns(() => "short");
            //mockVolumeCharacterModel.Setup(m => m.Description).Returns(() => "long");
            // <None>
            // Related Objects
            mockVolumeCharacterModel.Setup(m => m.VolumeId).Returns(() => 1);
            mockVolumeCharacterModel.Setup(m => m.Volume).Returns(() => new VolumeModel());
            mockVolumeCharacterModel.Setup(m => m.CharacterId).Returns(() => 1);
            mockVolumeCharacterModel.Setup(m => m.Character).Returns(() => new CharacterModel());
            // Associated Objects
            // <None>
            // Return
            return mockVolumeCharacterModel;
        }

        public static Mock<IVolumeCharacter> DoMockingSetupForVolumeCharacter(int idReturnValue = 0, string name = "Stephen King")
        {
            var mockVolumeCharacter = new Mock<IVolumeCharacter>();
            // Mock Functions
            mockVolumeCharacter.Setup(m => m.Id).Returns(() => idReturnValue);
            mockVolumeCharacter.Setup(m => m.Active).Returns(() => true);
            mockVolumeCharacter.Setup(m => m.CustomKey).Returns(() => "KING-STEPHEN");
            mockVolumeCharacter.Setup(m => m.ApiDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockVolumeCharacter.Setup(m => m.SiteDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockVolumeCharacter.Setup(m => m.CreatedDate).Returns(() => new System.DateTime(2015, 10, 1));
            mockVolumeCharacter.Setup(m => m.UpdatedDate).Returns(() => null);
            //mockVolumeCharacter.Setup(m => m.Name).Returns(() => name);
            //mockVolumeCharacter.Setup(m => m.ShortDescription).Returns(() => "short");
            //mockVolumeCharacter.Setup(m => m.Description).Returns(() => "long");
            // <None>
            // Related Objects
            mockVolumeCharacter.Setup(m => m.VolumeId).Returns(() => 1);
            mockVolumeCharacter.Setup(m => m.Volume).Returns(() => new Volume());
            mockVolumeCharacter.Setup(m => m.CharacterId).Returns(() => 1);
            mockVolumeCharacter.Setup(m => m.Character).Returns(() => new Character());
            // Associated Objects
            // <None>
            // Return
            return mockVolumeCharacter;
        }
    }

    public class VolumeCharacterMappingExtensionsTests
    {
        [Fact]
        public void Verify_MapToEntityExtension_CallsMapToEntity()
        {
            // Arrange
            var mockMapper = new Mock<VolumeCharacterMapper>();
            mockMapper.Setup(x => x.MapToEntity(It.IsAny<IVolumeCharacterModel>()));
            var mockModel = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacterModel(1);
            VolumeCharacterMapperExtensions.OverrideMapper(mockMapper.Object);
            // Act
            mockModel.Object.MapToEntity();
            // Assert
            mockMapper.Verify(x => x.MapToEntity(It.IsAny<IVolumeCharacterModel>()), Times.Once);
        }

        //[Fact]
        //public void Verify_MapToEntityWithExistingExtension_CallsMapToEntity()
        //{
        //    // Arrange
        //    var mockMapper = new Mock<VolumeCharacterMapper>();
        //    mockMapper.Setup(x => x.MapToEntity(It.IsAny<IVolumeCharacterModel>(), ref It.IsAny<IVolumeCharacter>()));
        //    var mockModel = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacterModel(1);
        //    var mockEntity = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacter(1);
        //    VolumeCharacterMapperExtensions.OverrideMapper(mockMapper.Object);
        //    // Act
        //    mockModel.Object.MapToEntity(ref mockEntity);
        //    // Assert
        //    mockMapper.Verify(x => x.MapToEntity(It.IsAny<IVolumeCharacterModel>(), ref It.IsAny<IVolumeCharacter>()), Times.Once);
        //}

        [Fact]
        public void Verify_MapToModelExtension_CallsMapToModel()
        {
            // Arrange
            var mockMapper = new Mock<VolumeCharacterMapper>();
            mockMapper.Setup(x => x.MapToModel(It.IsAny<IVolumeCharacter>()));
            var mockEntity = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacter(1);
            VolumeCharacterMapperExtensions.OverrideMapper(mockMapper.Object);
            // Act
            mockEntity.Object.MapToModel();
            // Assert
            mockMapper.Verify(x => x.MapToModel(It.IsAny<IVolumeCharacter>()), Times.Once);
        }

        [Fact]
        public void Verify_MapToModelLiteExtension_CallsMapToModel()
        {
            // Arrange
            var mockMapper = new Mock<VolumeCharacterMapper>();
            mockMapper.Setup(x => x.MapToModelLite(It.IsAny<IVolumeCharacter>()));
            var mockEntity = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacter(1);
            VolumeCharacterMapperExtensions.OverrideMapper(mockMapper.Object);
            // Act
            mockEntity.Object.MapToModelLite();
            // Assert
            mockMapper.Verify(x => x.MapToModelLite(It.IsAny<IVolumeCharacter>()), Times.Once);
        }

        [Fact]
        public void Verify_MapToModelListingExtension_CallsMapToModel()
        {
            // Arrange
            var mockMapper = new Mock<VolumeCharacterMapper>();
            mockMapper.Setup(x => x.MapToModelListing(It.IsAny<IVolumeCharacter>()));
            var mockEntity = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacter(1);
            VolumeCharacterMapperExtensions.OverrideMapper(mockMapper.Object);
            // Act
            mockEntity.Object.MapToModelListing();
            // Assert
            mockMapper.Verify(x => x.MapToModelListing(It.IsAny<IVolumeCharacter>()), Times.Once);
        }

        [Fact]
        public void Verify_MapToSearchModelExtension_CallsMapToModel()
        {
            // Arrange
            var mockMapper = new Mock<VolumeCharacterMapper>();
            mockMapper.Setup(x => x.MapToSearchModel(It.IsAny<IVolumeCharacterModel>()));
            var mockModel = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacterModel(1);
            VolumeCharacterMapperExtensions.OverrideMapper(mockMapper.Object);
            // Act
            mockModel.Object.MapToSearchModel();
            // Assert
            mockMapper.Verify(x => x.MapToSearchModel(It.IsAny<IVolumeCharacterModel>()), Times.Once);
        }

        [Fact]
        public void Verify_AreEqualExtension_CallsAreEqual()
        {
            // Arrange
            var mockMapper = new Mock<VolumeCharacterMapper>();
            mockMapper.Setup(x => x.AreEqual(It.IsAny<IVolumeCharacterModel>(), It.IsAny<IVolumeCharacter>()));
            VolumeCharacterMapperExtensions.OverrideMapper(mockMapper.Object);
            var mockModel = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacterModel(1);
            var mockEntity = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacter(1);
            // Act
            mockModel.Object.AreEqual(mockEntity.Object);
            // Assert
            mockMapper.Verify(x => x.AreEqual(It.IsAny<IVolumeCharacterModel>(), It.IsAny<IVolumeCharacter>()), Times.Once);
        }
    }

    public class VolumeCharactersMappingTests
    {
        [Fact]
        public void Verify_MapToEntity_AssignsVolumeCharacterProperties()
        {
            // Arrange
            var mapper = new VolumeCharacterMapper();
            var model = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacterModel();
            // Act
            var entity = mapper.MapToEntity(model.Object);
            // Assert
            // <None>
            // Related Objects
            Assert.Equal(model.Object.VolumeId, entity.VolumeId);
            Assert.Equal(model.Object.CharacterId, entity.CharacterId);
            // Associated Objects
            // <None>
        }

        [Fact]
        public void Verify_MapToEntity_WithExistingEntity_AssignsVolumeCharacterProperties()
        {
            // Arrange
            var mapper = new VolumeCharacterMapper();
            var model = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacterModel();
            // Act
            IVolumeCharacter existingEntity = new VolumeCharacter { Id = 1 };
            mapper.MapToEntity(model.Object, ref existingEntity);
            // Assert
            // <None>
            // Related Objects
            Assert.Equal(model.Object.VolumeId, existingEntity.VolumeId);
            Assert.Equal(model.Object.CharacterId, existingEntity.CharacterId);
            // Associated Objects
            // <None>
        }

        [Fact]
        public void Verify_MapToModel_AssignsVolumeCharacterProperties()
        {
            // Arrange
            var mapper = new VolumeCharacterMapper();
            var entity = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacter();
            // Act
            var model = mapper.MapToModel(entity.Object);
            // Assert
            // <None>
            // Related Objects
            Assert.Equal(entity.Object.VolumeId, model.VolumeId);
            Assert.Equal(entity.Object.CharacterId, model.CharacterId);
            // Associated Objects
            // <None>
        }

        [Fact]
        public void Verify_MapToModelLite_AssignsLiteOnlyVolumeCharacterProperties()
        {
            // Arrange
            var mapper = new VolumeCharacterMapper();
            var entity = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacter();
            // Act
            var model = mapper.MapToModelLite(entity.Object);
            // Assert
            // <None>
            // Related Objects
            Assert.Equal(entity.Object.VolumeId, model.VolumeId);
            Assert.Equal(entity.Object.CharacterId, model.CharacterId);
        }

        [Fact]
        public void Verify_MapToModelListing_AssignsListingOnlyVolumeCharacterProperties()
        {
            // Arrange
            var mapper = new VolumeCharacterMapper();
            var entity = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacter();
            // Act
            var model = mapper.MapToModelListing(entity.Object);
            // Assert
            // <None>
            // Related Objects
            Assert.Equal(entity.Object.VolumeId, model.VolumeId);
            Assert.Equal(entity.Object.CharacterId, model.CharacterId);
            // Return Entity
        }

        [Fact]
        public void Verify_MapToSearchModel_AssignsVolumeCharacterSearchProperties()
        {
            // Arrange
            var mapper = new VolumeCharacterMapper();
            var model = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacterModel();
            // Act
            var searchModel = mapper.MapToSearchModel(model.Object);
            // Assert
            Assert.Equal(model.Object.VolumeId, searchModel.VolumeId);
            Assert.Equal(model.Object.Volume?.CustomKey, searchModel.VolumeCustomKey);
            Assert.Equal(model.Object.Volume?.ApiDetailUrl, searchModel.VolumeApiDetailUrl);
            Assert.Equal(model.Object.Volume?.SiteDetailUrl, searchModel.VolumeSiteDetailUrl);
            Assert.Equal(model.Object.Volume?.Name, searchModel.VolumeName);
            Assert.Equal(model.Object.Volume?.ShortDescription, searchModel.VolumeShortDescription);
            Assert.Equal(model.Object.Volume?.Description, searchModel.VolumeDescription);
            Assert.Equal(model.Object.CharacterId, searchModel.CharacterId);
            Assert.Equal(model.Object.Character?.CustomKey, searchModel.CharacterCustomKey);
            Assert.Equal(model.Object.Character?.ApiDetailUrl, searchModel.CharacterApiDetailUrl);
            Assert.Equal(model.Object.Character?.SiteDetailUrl, searchModel.CharacterSiteDetailUrl);
            Assert.Equal(model.Object.Character?.Name, searchModel.CharacterName);
            Assert.Equal(model.Object.Character?.ShortDescription, searchModel.CharacterShortDescription);
            Assert.Equal(model.Object.Character?.Description, searchModel.CharacterDescription);
        }

        [Fact]
        public void Verify_AreEqual_WithEqualObjects_ReturnsTrue()
        {
            // Arrange
            var mapper = new VolumeCharacterMapper();
            var model = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacterModel(1);
            var entity = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacter(1);
            // Act
            var result = mapper.AreEqual(model.Object, entity.Object);
            // Assert
            Assert.True(result);
        }

        [Fact]
        public void Verify_AreEqual_WithDifferentObjects_ReturnsFalse()
        {
            // Arrange
            var mapper = new VolumeCharacterMapper();
            var model = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacterModel(1);
            var entity = VolumeCharactersMockingSetup.DoMockingSetupForVolumeCharacter(2);
            // Act
            var result = mapper.AreEqual(model.Object, entity.Object);
            // Assert
            Assert.False(result);
        }
    }
}
