// <auto-generated>
// <copyright file="Episodes.IEpisodeTeamBusinessWorkflowsTests.cs" company="jothay.com">
// Copyright (c) 2015 Jothay Tech, Inc. All rights reserved.
// </copyright>
// <summary>Implements the EpisodeTeamsRepository Class.</summary>
// <remarks>This file was auto-generated using BusinessWorkflowsTestingFileMaster.tt in
// ComicVineScraper.API.BusinessWorkflows.Testing\CodeGenerator</remarks>
// </auto-generated>
namespace ComicVineScraper.API.Testing.BusinessWorkflows.Episodes
{
    using System.Collections.Generic;
    using API.BusinessWorkflows;
    using API.Mappings;
    using DataModel.Schema;
    using Interfaces.DataModels;
    using Interfaces.Mappers;
    using Interfaces.Models;
    using Interfaces.Repositories;
    using Interfaces.SearchModels;
    using Models;
    using Moq;
    using Xunit;

    public static class EpisodeTeamsMockingSetup
    {
        public static Mock<IEpisodeTeamModel> DoMockingSetupForEpisodeTeamModel(int idReturnValue = 0, string name = "Stephen King")
        {
            var mockEpisodeTeamModel = new Mock<IEpisodeTeamModel>();
            // Mock Functions
            mockEpisodeTeamModel.Setup(m => m.Id).Returns(() => idReturnValue);
            mockEpisodeTeamModel.Setup(m => m.Active).Returns(() => true);
            mockEpisodeTeamModel.Setup(m => m.CustomKey).Returns(() => "KING-STEPHEN");
            mockEpisodeTeamModel.Setup(m => m.ApiDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockEpisodeTeamModel.Setup(m => m.SiteDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockEpisodeTeamModel.Setup(m => m.CreatedDate).Returns(() => new System.DateTime(2015, 10, 1));
            mockEpisodeTeamModel.Setup(m => m.UpdatedDate).Returns(() => null);
            // <None>
            // Related Objects
            mockEpisodeTeamModel.Setup(m => m.EpisodeId).Returns(() => 1);
            mockEpisodeTeamModel.Setup(m => m.Episode).Returns(() => new EpisodeModel());
            mockEpisodeTeamModel.Setup(m => m.TeamId).Returns(() => 1);
            mockEpisodeTeamModel.Setup(m => m.Team).Returns(() => new TeamModel());
            // Associated Objects
            // <None>
            // Return
            return mockEpisodeTeamModel;
        }

        public static Mock<IEpisodeTeam> DoMockingSetupForEpisodeTeam(int idReturnValue = 0, string name = "Stephen King")
        {
            var mockEpisodeTeam = new Mock<IEpisodeTeam>();
            // Mock Functions
            mockEpisodeTeam.Setup(m => m.Id).Returns(() => idReturnValue);
            mockEpisodeTeam.Setup(m => m.Active).Returns(() => true);
            mockEpisodeTeam.Setup(m => m.CustomKey).Returns(() => "KING-STEPHEN");
            mockEpisodeTeam.Setup(m => m.ApiDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockEpisodeTeam.Setup(m => m.SiteDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockEpisodeTeam.Setup(m => m.CreatedDate).Returns(() => new System.DateTime(2015, 10, 1));
            mockEpisodeTeam.Setup(m => m.UpdatedDate).Returns(() => null);
            // <None>
            // Related Objects
            mockEpisodeTeam.Setup(m => m.EpisodeId).Returns(() => 1);
            mockEpisodeTeam.Setup(m => m.Episode).Returns(() => new Episode());
            mockEpisodeTeam.Setup(m => m.TeamId).Returns(() => 1);
            mockEpisodeTeam.Setup(m => m.Team).Returns(() => new Team());
            // Associated Objects
            // <None>
            // Return
            return mockEpisodeTeam;
        }

        public static Mock<IEpisodeTeamsRepository> DoMockingSetupForRepository()
        {
            var mockEpisodeTeamsRepository = new Mock<IEpisodeTeamsRepository>();
            // Mock Functions
            mockEpisodeTeamsRepository.Setup(m => m.Get(It.IsAny<int>()))
                .Returns(() => new Mock<IEpisodeTeam>().Object);
            mockEpisodeTeamsRepository.Setup(m => m.Get(It.IsAny<string>()))
                .Returns(() => new Mock<IEpisodeTeam>().Object);
            mockEpisodeTeamsRepository.Setup(m => m.List)
                .Returns(() => new Mock<List<IEpisodeTeam>>().Object);
            mockEpisodeTeamsRepository.Setup(m => m.Search(It.IsAny<IEpisodeTeamSearchModel>(), It.IsAny<bool>()))
                .Returns(() => new Mock<List<IEpisodeTeam>>().Object);
            mockEpisodeTeamsRepository.Setup(m => m.Add(It.IsAny<IEpisodeTeam>()));
            mockEpisodeTeamsRepository.Setup(m => m.Remove(It.IsAny<IEpisodeTeam>()));
            mockEpisodeTeamsRepository.Setup(m => m.Deactivate(It.IsAny<IEpisodeTeam>()));
            mockEpisodeTeamsRepository.Setup(m => m.Update(It.IsAny<IEpisodeTeam>()));
            // Return
            return mockEpisodeTeamsRepository;
        }
    }

    public class EpisodeTeamsBusinessWorkflowsTests
    {
        #region Read
        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Get_ByID_Should_ReturnTheCorrectObjectType()
        {
            // Arrange
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, new EpisodeTeamMapper());
            // Act
            var person = businessWorkflow.Get(1);
            // Assert
            Assert.IsType<EpisodeTeamModel>(person);
        }

        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Get_ByKey_Should_ReturnTheCorrectObject()
        {
            // Arrange
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, new EpisodeTeamMapper());
            // Act
            var person = businessWorkflow.Get("KING-STEPHEN");
            // Assert
            Assert.IsType<EpisodeTeamModel>(person);
        }

        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Search_Should_ReturnAListOfEpisodeTeams()
        {
            // Arrange
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            var searchModel = new Mock<IEpisodeTeamSearchModel>();
            var mockEpisodeTeamsMapper = new Mock<IEpisodeTeamMapper>();
            mockEpisodeTeamsMapper.Setup(m => m.AreEqual(It.IsAny<IEpisodeTeamModel>(), It.IsAny<IEpisodeTeam>())).Returns(() => true);
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, mockEpisodeTeamsMapper.Object);
            // Act
            businessWorkflow.Search(searchModel.Object);
            // Assert
            mockEpisodeTeamsRepository.Verify(m => m.Search(It.IsAny<IEpisodeTeamSearchModel>(), It.IsAny<bool>()), Times.Once);
        }

        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Search_AsListing_Should_ReturnAListOfEpisodeTeamsWithDataMatchingSearchParametersWithListingMapping()
        {
            // Arrange
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            var searchModel = new Mock<IEpisodeTeamSearchModel>();
            var mockEpisodeTeamsMapper = new Mock<IEpisodeTeamMapper>();
            mockEpisodeTeamsMapper.Setup(m => m.AreEqual(It.IsAny<IEpisodeTeamModel>(), It.IsAny<IEpisodeTeam>())).Returns(() => true);
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, mockEpisodeTeamsMapper.Object);
            // Act
            businessWorkflow.Search(searchModel.Object, true);
            // Assert
            mockEpisodeTeamsRepository.Verify(m => m.Search(It.IsAny<IEpisodeTeamSearchModel>(), It.IsAny<bool>()), Times.Once);
        }
        #endregion
        #region Create
        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Create_Should_AddANewEntityObjectToTheDatabase()
        {
            // Arrange
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            mockEpisodeTeamsRepository.Setup(m => m.Search(It.IsAny<IEpisodeTeamSearchModel>(), It.IsAny<bool>()))
                .Returns(() => new Mock<List<IEpisodeTeam>>().Object);
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, new EpisodeTeamMapper());
            var model = EpisodeTeamsMockingSetup.DoMockingSetupForEpisodeTeamModel();
            // Act
            try { businessWorkflow.Create(model.Object); } catch { /* Ignored */ }
            // Assert
            mockEpisodeTeamsRepository.Verify(m => m.Add(It.IsAny<IEpisodeTeam>()), Times.Once);
        }
        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Create_WithDuplicateData_Should_NotAddAndReturnOriginal()
        {
            // Arrange
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            var mockEpisodeTeam = EpisodeTeamsMockingSetup.DoMockingSetupForEpisodeTeam(1);
            mockEpisodeTeamsRepository.Setup(m => m.Search(It.IsAny<IEpisodeTeamSearchModel>(), It.IsAny<bool>()))
                .Returns(() => new List<IEpisodeTeam> { mockEpisodeTeam.Object } );
            mockEpisodeTeamsRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => mockEpisodeTeam.Object);
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, new EpisodeTeamMapper());
            var model = EpisodeTeamsMockingSetup.DoMockingSetupForEpisodeTeamModel();
            // Act
            try { businessWorkflow.Create(model.Object); }
            catch { /* ignored, the Get call at the end doesn't work because don't get a real entity with id on it */ }
            // Assert
            mockEpisodeTeamsRepository.Verify(m => m.Add(It.IsAny<IEpisodeTeam>()), Times.Never);
        }
        #endregion
        #region Update
        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Update_Should_SetUpdatedDate()
        {
            // Arrange
            var mockEpisodeTeam = EpisodeTeamsMockingSetup.DoMockingSetupForEpisodeTeam(1);
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            mockEpisodeTeamsRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => mockEpisodeTeam.Object);
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, new EpisodeTeamMapper());
            var expectedName = "Stephen King (2)";
            var model = EpisodeTeamsMockingSetup.DoMockingSetupForEpisodeTeamModel(1, expectedName);
            // Act
            businessWorkflow.Update(model.Object);
            // Assert
            mockEpisodeTeam.Verify(m => m.UpdatedDate, Times.Once);
        }
        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Update_WithDuplicateData_Should_NotAddAndReturnOriginal()
        {
            // Arrange
            var entity = EpisodeTeamsMockingSetup.DoMockingSetupForEpisodeTeam(1);
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            mockEpisodeTeamsRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => entity.Object);
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, new EpisodeTeamMapper());
            var model = EpisodeTeamsMockingSetup.DoMockingSetupForEpisodeTeamModel(1);
            IEpisodeTeamModel result = null;
            // Act
            try { result = businessWorkflow.Update(model.Object); }
            catch { /* ignored, the Get call at the end doesn't work because don't get a real entity with id on it */ }
            // Assert
            Assert.NotNull(result);
            Assert.Equal("/TEST/KING-STEPHEN", result.ApiDetailUrl);
            Assert.Null(result.UpdatedDate);
        }
        #endregion
        #region Deactivate
        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Deactivate_ByID_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            var mockEpisodeTeamsMapper = new Mock<IEpisodeTeamMapper>();
            mockEpisodeTeamsMapper.Setup(m => m.AreEqual(It.IsAny<IEpisodeTeamModel>(), It.IsAny<IEpisodeTeam>())).Returns(() => true);
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, mockEpisodeTeamsMapper.Object);
            mockEpisodeTeamsRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => new Mock<IEpisodeTeam>().Object);
            mockEpisodeTeamsRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Deactivate(1);
            // Assert
            mockEpisodeTeamsRepository.Verify(m => m.Deactivate(It.IsAny<IEpisodeTeam>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Deactivate_ByKey_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            var mockEpisodeTeamsMapper = new Mock<IEpisodeTeamMapper>();
            mockEpisodeTeamsMapper.Setup(m => m.AreEqual(It.IsAny<IEpisodeTeamModel>(), It.IsAny<IEpisodeTeam>())).Returns(() => true);
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, mockEpisodeTeamsMapper.Object);
            mockEpisodeTeamsRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => new Mock<IEpisodeTeam>().Object);
            mockEpisodeTeamsRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Deactivate("KING-STEPHEN");
            // Assert
            mockEpisodeTeamsRepository.Verify(m => m.Deactivate(It.IsAny<IEpisodeTeam>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Deactivate_ByID_ANonExistingEntity_Should_ThrowAnInvalidOperationException()
        {
            // Arrange
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            mockEpisodeTeamsRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => null);
            var mockEpisodeTeamsMapper = new Mock<IEpisodeTeamMapper>();
            mockEpisodeTeamsMapper.Setup(m => m.AreEqual(It.IsAny<IEpisodeTeamModel>(), It.IsAny<IEpisodeTeam>())).Returns(() => true);
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, mockEpisodeTeamsMapper.Object);
            // Act/Assert
            Assert.Throws<System.InvalidOperationException>(() => businessWorkflow.Deactivate(1));
        }

        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Deactivate_ByKey_ANonExistingEntity_Should_ThrowAnInvalidOperationException()
        {
            // Arrange
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            mockEpisodeTeamsRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => null);
            var mockEpisodeTeamsMapper = new Mock<IEpisodeTeamMapper>();
            mockEpisodeTeamsMapper.Setup(m => m.AreEqual(It.IsAny<IEpisodeTeamModel>(), It.IsAny<IEpisodeTeam>())).Returns(() => true);
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, mockEpisodeTeamsMapper.Object);
            // Act/Assert
            Assert.Throws<System.InvalidOperationException>(() => businessWorkflow.Deactivate("TEST"));
        }
        #endregion
        #region Remove
        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Remove_ByID_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            var mockEpisodeTeamsMapper = new Mock<IEpisodeTeamMapper>();
            mockEpisodeTeamsMapper.Setup(m => m.AreEqual(It.IsAny<IEpisodeTeamModel>(), It.IsAny<IEpisodeTeam>())).Returns(() => true);
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, mockEpisodeTeamsMapper.Object);
            mockEpisodeTeamsRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => new Mock<IEpisodeTeam>().Object);
            mockEpisodeTeamsRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Remove(1);
            // Assert
            mockEpisodeTeamsRepository.Verify(m => m.Remove(It.IsAny<IEpisodeTeam>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Remove_ByKey_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            var mockEpisodeTeamsMapper = new Mock<IEpisodeTeamMapper>();
            mockEpisodeTeamsMapper.Setup(m => m.AreEqual(It.IsAny<IEpisodeTeamModel>(), It.IsAny<IEpisodeTeam>())).Returns(() => true);
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, mockEpisodeTeamsMapper.Object);
            mockEpisodeTeamsRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => new Mock<IEpisodeTeam>().Object);
            mockEpisodeTeamsRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Remove("KING-STEPHEN");
            // Assert
            mockEpisodeTeamsRepository.Verify(m => m.Remove(It.IsAny<IEpisodeTeam>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact][Trait("Category", "EpisodeTeams")]
        public void Verify_Remove_ANonExistingEntity_Should_ReturnTrue()
        {
            // Arrange
            var mockEpisodeTeamsRepository = EpisodeTeamsMockingSetup.DoMockingSetupForRepository();
            mockEpisodeTeamsRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => null);
            var businessWorkflow = new EpisodeTeamsBusinessWorkflow(mockEpisodeTeamsRepository.Object, new EpisodeTeamMapper());
            // Act
            var result = businessWorkflow.Remove("DOESNT-EXIST");
            // Assert
            Assert.Equal(true, result);
        }
        #endregion
    }
}
