// <auto-generated>
// <copyright file="Issues.IIssueAliasBusinessWorkflowsTests.cs" company="jothay.com">
// Copyright (c) 2015 Jothay Tech, Inc. All rights reserved.
// </copyright>
// <summary>Implements the IssueAliasesRepository Class.</summary>
// <remarks>This file was auto-generated using BusinessWorkflowsTestingFileMaster.tt in
// ComicVineScraper.API.BusinessWorkflows.Testing\CodeGenerator</remarks>
// </auto-generated>
namespace ComicVineScraper.API.Testing.BusinessWorkflows.Issues
{
    using System.Collections.Generic;
    using API.BusinessWorkflows;
    using API.Mappings;
    using DataModel.Schema;
    using Interfaces.DataModels;
    using Interfaces.Mappers;
    using Interfaces.Models;
    using Interfaces.Repositories;
    using Interfaces.SearchModels;
    using Models;
    using Moq;
    using Xunit;

    public static class IssueAliasesMockingSetup
    {
        public static Mock<IIssueAliasModel> DoMockingSetupForIssueAliasModel(int idReturnValue = 0, string name = "Stephen King")
        {
            var mockIssueAliasModel = new Mock<IIssueAliasModel>();
            // Mock Functions
            mockIssueAliasModel.Setup(m => m.Id).Returns(() => idReturnValue);
            mockIssueAliasModel.Setup(m => m.Active).Returns(() => true);
            mockIssueAliasModel.Setup(m => m.CustomKey).Returns(() => "KING-STEPHEN");
            mockIssueAliasModel.Setup(m => m.ApiDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockIssueAliasModel.Setup(m => m.SiteDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockIssueAliasModel.Setup(m => m.CreatedDate).Returns(() => new System.DateTime(2015, 10, 1));
            mockIssueAliasModel.Setup(m => m.UpdatedDate).Returns(() => null);
            // <None>
            // Related Objects
            mockIssueAliasModel.Setup(m => m.IssueId).Returns(() => 1);
            mockIssueAliasModel.Setup(m => m.Issue).Returns(() => new IssueModel());
            // Associated Objects
            // <None>
            // Return
            return mockIssueAliasModel;
        }

        public static Mock<IIssueAlias> DoMockingSetupForIssueAlias(int idReturnValue = 0, string name = "Stephen King")
        {
            var mockIssueAlias = new Mock<IIssueAlias>();
            // Mock Functions
            mockIssueAlias.Setup(m => m.Id).Returns(() => idReturnValue);
            mockIssueAlias.Setup(m => m.Active).Returns(() => true);
            mockIssueAlias.Setup(m => m.CustomKey).Returns(() => "KING-STEPHEN");
            mockIssueAlias.Setup(m => m.ApiDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockIssueAlias.Setup(m => m.SiteDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockIssueAlias.Setup(m => m.CreatedDate).Returns(() => new System.DateTime(2015, 10, 1));
            mockIssueAlias.Setup(m => m.UpdatedDate).Returns(() => null);
            // <None>
            // Related Objects
            mockIssueAlias.Setup(m => m.IssueId).Returns(() => 1);
            mockIssueAlias.Setup(m => m.Issue).Returns(() => new Issue());
            // Associated Objects
            // <None>
            // Return
            return mockIssueAlias;
        }

        public static Mock<IIssueAliasesRepository> DoMockingSetupForRepository()
        {
            var mockIssueAliasesRepository = new Mock<IIssueAliasesRepository>();
            // Mock Functions
            mockIssueAliasesRepository.Setup(m => m.Get(It.IsAny<int>()))
                .Returns(() => new Mock<IIssueAlias>().Object);
            mockIssueAliasesRepository.Setup(m => m.Get(It.IsAny<string>()))
                .Returns(() => new Mock<IIssueAlias>().Object);
            mockIssueAliasesRepository.Setup(m => m.List)
                .Returns(() => new Mock<List<IIssueAlias>>().Object);
            mockIssueAliasesRepository.Setup(m => m.Search(It.IsAny<IIssueAliasSearchModel>(), It.IsAny<bool>()))
                .Returns(() => new Mock<List<IIssueAlias>>().Object);
            mockIssueAliasesRepository.Setup(m => m.Add(It.IsAny<IIssueAlias>()));
            mockIssueAliasesRepository.Setup(m => m.Remove(It.IsAny<IIssueAlias>()));
            mockIssueAliasesRepository.Setup(m => m.Deactivate(It.IsAny<IIssueAlias>()));
            mockIssueAliasesRepository.Setup(m => m.Update(It.IsAny<IIssueAlias>()));
            // Return
            return mockIssueAliasesRepository;
        }
    }

    public class IssueAliasesBusinessWorkflowsTests
    {
        #region Read
        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Get_ByID_Should_ReturnTheCorrectObjectType()
        {
            // Arrange
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, new IssueAliasMapper());
            // Act
            var person = businessWorkflow.Get(1);
            // Assert
            Assert.IsType<IssueAliasModel>(person);
        }

        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Get_ByKey_Should_ReturnTheCorrectObject()
        {
            // Arrange
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, new IssueAliasMapper());
            // Act
            var person = businessWorkflow.Get("KING-STEPHEN");
            // Assert
            Assert.IsType<IssueAliasModel>(person);
        }

        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Search_Should_ReturnAListOfIssueAliases()
        {
            // Arrange
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            var searchModel = new Mock<IIssueAliasSearchModel>();
            var mockIssueAliasesMapper = new Mock<IIssueAliasMapper>();
            mockIssueAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IIssueAliasModel>(), It.IsAny<IIssueAlias>())).Returns(() => true);
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, mockIssueAliasesMapper.Object);
            // Act
            businessWorkflow.Search(searchModel.Object);
            // Assert
            mockIssueAliasesRepository.Verify(m => m.Search(It.IsAny<IIssueAliasSearchModel>(), It.IsAny<bool>()), Times.Once);
        }

        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Search_AsListing_Should_ReturnAListOfIssueAliasesWithDataMatchingSearchParametersWithListingMapping()
        {
            // Arrange
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            var searchModel = new Mock<IIssueAliasSearchModel>();
            var mockIssueAliasesMapper = new Mock<IIssueAliasMapper>();
            mockIssueAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IIssueAliasModel>(), It.IsAny<IIssueAlias>())).Returns(() => true);
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, mockIssueAliasesMapper.Object);
            // Act
            businessWorkflow.Search(searchModel.Object, true);
            // Assert
            mockIssueAliasesRepository.Verify(m => m.Search(It.IsAny<IIssueAliasSearchModel>(), It.IsAny<bool>()), Times.Once);
        }
        #endregion
        #region Create
        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Create_Should_AddANewEntityObjectToTheDatabase()
        {
            // Arrange
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            mockIssueAliasesRepository.Setup(m => m.Search(It.IsAny<IIssueAliasSearchModel>(), It.IsAny<bool>()))
                .Returns(() => new Mock<List<IIssueAlias>>().Object);
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, new IssueAliasMapper());
            var model = IssueAliasesMockingSetup.DoMockingSetupForIssueAliasModel();
            // Act
            try { businessWorkflow.Create(model.Object); } catch { /* Ignored */ }
            // Assert
            mockIssueAliasesRepository.Verify(m => m.Add(It.IsAny<IIssueAlias>()), Times.Once);
        }
        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Create_WithDuplicateData_Should_NotAddAndReturnOriginal()
        {
            // Arrange
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            var mockIssueAlias = IssueAliasesMockingSetup.DoMockingSetupForIssueAlias(1);
            mockIssueAliasesRepository.Setup(m => m.Search(It.IsAny<IIssueAliasSearchModel>(), It.IsAny<bool>()))
                .Returns(() => new List<IIssueAlias> { mockIssueAlias.Object } );
            mockIssueAliasesRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => mockIssueAlias.Object);
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, new IssueAliasMapper());
            var model = IssueAliasesMockingSetup.DoMockingSetupForIssueAliasModel();
            // Act
            try { businessWorkflow.Create(model.Object); }
            catch { /* ignored, the Get call at the end doesn't work because don't get a real entity with id on it */ }
            // Assert
            mockIssueAliasesRepository.Verify(m => m.Add(It.IsAny<IIssueAlias>()), Times.Never);
        }
        #endregion
        #region Update
        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Update_Should_SetUpdatedDate()
        {
            // Arrange
            var mockIssueAlias = IssueAliasesMockingSetup.DoMockingSetupForIssueAlias(1);
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            mockIssueAliasesRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => mockIssueAlias.Object);
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, new IssueAliasMapper());
            var expectedName = "Stephen King (2)";
            var model = IssueAliasesMockingSetup.DoMockingSetupForIssueAliasModel(1, expectedName);
            // Act
            businessWorkflow.Update(model.Object);
            // Assert
            mockIssueAlias.Verify(m => m.UpdatedDate, Times.Once);
        }
        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Update_WithDuplicateData_Should_NotAddAndReturnOriginal()
        {
            // Arrange
            var entity = IssueAliasesMockingSetup.DoMockingSetupForIssueAlias(1);
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            mockIssueAliasesRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => entity.Object);
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, new IssueAliasMapper());
            var model = IssueAliasesMockingSetup.DoMockingSetupForIssueAliasModel(1);
            IIssueAliasModel result = null;
            // Act
            try { result = businessWorkflow.Update(model.Object); }
            catch { /* ignored, the Get call at the end doesn't work because don't get a real entity with id on it */ }
            // Assert
            Assert.NotNull(result);
            Assert.Equal("/TEST/KING-STEPHEN", result.ApiDetailUrl);
            Assert.Null(result.UpdatedDate);
        }
        #endregion
        #region Deactivate
        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Deactivate_ByID_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            var mockIssueAliasesMapper = new Mock<IIssueAliasMapper>();
            mockIssueAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IIssueAliasModel>(), It.IsAny<IIssueAlias>())).Returns(() => true);
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, mockIssueAliasesMapper.Object);
            mockIssueAliasesRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => new Mock<IIssueAlias>().Object);
            mockIssueAliasesRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Deactivate(1);
            // Assert
            mockIssueAliasesRepository.Verify(m => m.Deactivate(It.IsAny<IIssueAlias>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Deactivate_ByKey_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            var mockIssueAliasesMapper = new Mock<IIssueAliasMapper>();
            mockIssueAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IIssueAliasModel>(), It.IsAny<IIssueAlias>())).Returns(() => true);
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, mockIssueAliasesMapper.Object);
            mockIssueAliasesRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => new Mock<IIssueAlias>().Object);
            mockIssueAliasesRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Deactivate("KING-STEPHEN");
            // Assert
            mockIssueAliasesRepository.Verify(m => m.Deactivate(It.IsAny<IIssueAlias>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Deactivate_ByID_ANonExistingEntity_Should_ThrowAnInvalidOperationException()
        {
            // Arrange
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            mockIssueAliasesRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => null);
            var mockIssueAliasesMapper = new Mock<IIssueAliasMapper>();
            mockIssueAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IIssueAliasModel>(), It.IsAny<IIssueAlias>())).Returns(() => true);
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, mockIssueAliasesMapper.Object);
            // Act/Assert
            Assert.Throws<System.InvalidOperationException>(() => businessWorkflow.Deactivate(1));
        }

        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Deactivate_ByKey_ANonExistingEntity_Should_ThrowAnInvalidOperationException()
        {
            // Arrange
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            mockIssueAliasesRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => null);
            var mockIssueAliasesMapper = new Mock<IIssueAliasMapper>();
            mockIssueAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IIssueAliasModel>(), It.IsAny<IIssueAlias>())).Returns(() => true);
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, mockIssueAliasesMapper.Object);
            // Act/Assert
            Assert.Throws<System.InvalidOperationException>(() => businessWorkflow.Deactivate("TEST"));
        }
        #endregion
        #region Remove
        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Remove_ByID_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            var mockIssueAliasesMapper = new Mock<IIssueAliasMapper>();
            mockIssueAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IIssueAliasModel>(), It.IsAny<IIssueAlias>())).Returns(() => true);
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, mockIssueAliasesMapper.Object);
            mockIssueAliasesRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => new Mock<IIssueAlias>().Object);
            mockIssueAliasesRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Remove(1);
            // Assert
            mockIssueAliasesRepository.Verify(m => m.Remove(It.IsAny<IIssueAlias>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Remove_ByKey_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            var mockIssueAliasesMapper = new Mock<IIssueAliasMapper>();
            mockIssueAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IIssueAliasModel>(), It.IsAny<IIssueAlias>())).Returns(() => true);
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, mockIssueAliasesMapper.Object);
            mockIssueAliasesRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => new Mock<IIssueAlias>().Object);
            mockIssueAliasesRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Remove("KING-STEPHEN");
            // Assert
            mockIssueAliasesRepository.Verify(m => m.Remove(It.IsAny<IIssueAlias>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact][Trait("Category", "IssueAliases")]
        public void Verify_Remove_ANonExistingEntity_Should_ReturnTrue()
        {
            // Arrange
            var mockIssueAliasesRepository = IssueAliasesMockingSetup.DoMockingSetupForRepository();
            mockIssueAliasesRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => null);
            var businessWorkflow = new IssueAliasesBusinessWorkflow(mockIssueAliasesRepository.Object, new IssueAliasMapper());
            // Act
            var result = businessWorkflow.Remove("DOESNT-EXIST");
            // Assert
            Assert.Equal(true, result);
        }
        #endregion
    }
}
