// <auto-generated>
// <copyright file="Movies.IMovieConceptRepository.cs" company="clarityventures.com">
// Copyright (c) 2015 Clarity Ventures, Inc. All rights reserved.
// </copyright>
// <summary>Implements the MovieConceptsRepository Class.</summary>
// <remarks>This file was autogenerated using BusinessWorkflowsTestingFileMaster.tt in ComicVine.API.BusinessWorkflows.Testing\BusinessWorkflows\CodeGenerator</remarks>
// </auto-generated>
namespace ComicVine.API.Testing.BusinessWorkflows.Movies
{
    using System.Collections.Generic;
    using API.BusinessWorkflows;
    using API.Mappings;
    using DataModel.Schema;
    using Interfaces.DataModels;
    using Interfaces.Mappers;
    using Interfaces.Models;
    using Interfaces.Repositories;
    using Interfaces.SearchModels;
    using Models;
    using Moq;
    using Xunit;

    public static class MovieConceptsMockingSetup
    {
        public static Mock<IMovieConceptModel> DoMockingSetupForMovieConceptModel(int idReturnValue = 0, string name = "Stephen King")
        {
            var mockMovieConceptModel = new Mock<IMovieConceptModel>();
            // Mock Functions
            mockMovieConceptModel.Setup(m => m.Id).Returns(() => idReturnValue);
            mockMovieConceptModel.Setup(m => m.Active).Returns(() => true);
            mockMovieConceptModel.Setup(m => m.CustomKey).Returns(() => "KING-STEPHEN");
            mockMovieConceptModel.Setup(m => m.ApiDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockMovieConceptModel.Setup(m => m.SiteDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockMovieConceptModel.Setup(m => m.CreatedDate).Returns(() => new System.DateTime(2015, 10, 1));
            mockMovieConceptModel.Setup(m => m.UpdatedDate).Returns(() => null);
            // <None>
            // Related Objects
            mockMovieConceptModel.Setup(m => m.MovieId).Returns(() => 1);
            mockMovieConceptModel.Setup(m => m.Movie).Returns(() => new MovieModel());
            mockMovieConceptModel.Setup(m => m.ConceptId).Returns(() => 1);
            mockMovieConceptModel.Setup(m => m.Concept).Returns(() => new ConceptModel());
            // Associated Objects
            // <None>
            // Return
            return mockMovieConceptModel;
        }

        public static Mock<IMovieConcept> DoMockingSetupForMovieConcept(int idReturnValue = 0, string name = "Stephen King")
        {
            var mockMovieConcept = new Mock<IMovieConcept>();
            // Mock Functions
            mockMovieConcept.Setup(m => m.Id).Returns(() => idReturnValue);
            mockMovieConcept.Setup(m => m.Active).Returns(() => true);
            mockMovieConcept.Setup(m => m.CustomKey).Returns(() => "KING-STEPHEN");
            mockMovieConcept.Setup(m => m.ApiDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockMovieConcept.Setup(m => m.SiteDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockMovieConcept.Setup(m => m.CreatedDate).Returns(() => new System.DateTime(2015, 10, 1));
            mockMovieConcept.Setup(m => m.UpdatedDate).Returns(() => null);
            // <None>
            // Related Objects
            mockMovieConcept.Setup(m => m.MovieId).Returns(() => 1);
            mockMovieConcept.Setup(m => m.Movie).Returns(() => new Movie());
            mockMovieConcept.Setup(m => m.ConceptId).Returns(() => 1);
            mockMovieConcept.Setup(m => m.Concept).Returns(() => new Concept());
            // Associated Objects
            // <None>
            // Return
            return mockMovieConcept;
        }

        public static Mock<IMovieConceptsRepository> DoMockingSetupForRepository()
        {
            var mockMovieConceptsRepository = new Mock<IMovieConceptsRepository>();
            // Mock Functions
            mockMovieConceptsRepository.Setup(m => m.Get(It.IsAny<int>()))
                .Returns(() => new Mock<IMovieConcept>().Object);
            mockMovieConceptsRepository.Setup(m => m.Get(It.IsAny<string>()))
                .Returns(() => new Mock<IMovieConcept>().Object);
            mockMovieConceptsRepository.Setup(m => m.List)
                .Returns(() => new Mock<List<IMovieConcept>>().Object);
            mockMovieConceptsRepository.Setup(m => m.Search(It.IsAny<IMovieConceptSearchModel>(), It.IsAny<bool>()))
                .Returns(() => new Mock<List<IMovieConcept>>().Object);
            mockMovieConceptsRepository.Setup(m => m.Add(It.IsAny<IMovieConcept>()));
            mockMovieConceptsRepository.Setup(m => m.Remove(It.IsAny<IMovieConcept>()));
            mockMovieConceptsRepository.Setup(m => m.Deactivate(It.IsAny<IMovieConcept>()));
            mockMovieConceptsRepository.Setup(m => m.Update(It.IsAny<IMovieConcept>()));
            // Return
            return mockMovieConceptsRepository;
        }
    }

    public class MovieConceptsBusinessWorkflowsTests
    {
        #region Read
        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Get_ByID_Should_ReturnTheCorrectObjectType()
        {
            // Arrange
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, new MovieConceptMapper());
            // Act
            var person = businessWorkflow.Get(1);
            // Assert
            Assert.IsType<MovieConceptModel>(person);
        }

        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Get_ByKey_Should_ReturnTheCorrectObject()
        {
            // Arrange
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, new MovieConceptMapper());
            // Act
            var person = businessWorkflow.Get("KING-STEPHEN");
            // Assert
            Assert.IsType<MovieConceptModel>(person);
        }

        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Search_Should_ReturnAListOfMovieConcepts()
        {
            // Arrange
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            var searchModel = new Mock<IMovieConceptSearchModel>();
            var mockMovieConceptsMapper = new Mock<IMovieConceptMapper>();
            mockMovieConceptsMapper.Setup(m => m.AreEqual(It.IsAny<IMovieConceptModel>(), It.IsAny<IMovieConcept>())).Returns(() => true);
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, mockMovieConceptsMapper.Object);
            // Act
            businessWorkflow.Search(searchModel.Object);
            // Assert
            mockMovieConceptsRepository.Verify(m => m.Search(It.IsAny<IMovieConceptSearchModel>(), It.IsAny<bool>()), Times.Once);
        }

        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Search_AsListing_Should_ReturnAListOfMovieConceptsWithDataMatchingSearchParametersWithListingMapping()
        {
            // Arrange
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            var searchModel = new Mock<IMovieConceptSearchModel>();
            var mockMovieConceptsMapper = new Mock<IMovieConceptMapper>();
            mockMovieConceptsMapper.Setup(m => m.AreEqual(It.IsAny<IMovieConceptModel>(), It.IsAny<IMovieConcept>())).Returns(() => true);
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, mockMovieConceptsMapper.Object);
            // Act
            businessWorkflow.Search(searchModel.Object, true);
            // Assert
            mockMovieConceptsRepository.Verify(m => m.Search(It.IsAny<IMovieConceptSearchModel>(), It.IsAny<bool>()), Times.Once);
        }
        #endregion
        #region Create
        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Create_Should_AddANewEntityObjectToTheDatabase()
        {
            // Arrange
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            mockMovieConceptsRepository.Setup(m => m.Search(It.IsAny<IMovieConceptSearchModel>(), It.IsAny<bool>()))
                .Returns(() => new Mock<List<IMovieConcept>>().Object);
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, new MovieConceptMapper());
            var model = MovieConceptsMockingSetup.DoMockingSetupForMovieConceptModel();
            // Act
            try { businessWorkflow.Create(model.Object); } catch { /* Ignored */ }
            // Assert
            mockMovieConceptsRepository.Verify(m => m.Add(It.IsAny<IMovieConcept>()), Times.Once);
        }
        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Create_WithDuplicateData_Should_NotAddAndReturnOriginal()
        {
            // Arrange
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            var mockMovieConcept = MovieConceptsMockingSetup.DoMockingSetupForMovieConcept(1);
            mockMovieConceptsRepository.Setup(m => m.Search(It.IsAny<IMovieConceptSearchModel>(), It.IsAny<bool>()))
                .Returns(() => new List<IMovieConcept> { mockMovieConcept.Object } );
            mockMovieConceptsRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => mockMovieConcept.Object);
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, new MovieConceptMapper());
            var model = MovieConceptsMockingSetup.DoMockingSetupForMovieConceptModel();
            // Act
            try { businessWorkflow.Create(model.Object); }
            catch { /* ignored, the Get call at the end doesn't work because don't get a real entity with id on it */ }
            // Assert
            mockMovieConceptsRepository.Verify(m => m.Add(It.IsAny<IMovieConcept>()), Times.Never);
        }
        #endregion
        #region Update
        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Update_Should_SetUpdatedDate()
        {
            // Arrange
            var mockMovieConcept = MovieConceptsMockingSetup.DoMockingSetupForMovieConcept(1);
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            mockMovieConceptsRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => mockMovieConcept.Object);
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, new MovieConceptMapper());
            var expectedName = "Stephen King (2)";
            var model = MovieConceptsMockingSetup.DoMockingSetupForMovieConceptModel(1, expectedName);
            // Act
            businessWorkflow.Update(model.Object);
            // Assert
            mockMovieConcept.Verify(m => m.UpdatedDate, Times.Once);
        }
        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Update_WithDuplicateData_Should_NotAddAndReturnOriginal()
        {
            // Arrange
            var entity = MovieConceptsMockingSetup.DoMockingSetupForMovieConcept(1);
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            mockMovieConceptsRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => entity.Object);
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, new MovieConceptMapper());
            var model = MovieConceptsMockingSetup.DoMockingSetupForMovieConceptModel(1);
            IMovieConceptModel result = null;
            // Act
            try { result = businessWorkflow.Update(model.Object); }
            catch { /* ignored, the Get call at the end doesn't work because don't get a real entity with id on it */ }
            // Assert
            Assert.NotNull(result);
            Assert.Equal("/TEST/KING-STEPHEN", result.ApiDetailUrl);
            Assert.Null(result.UpdatedDate);
        }
        #endregion
        #region Deactivate
        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Deactivate_ByID_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            var mockMovieConceptsMapper = new Mock<IMovieConceptMapper>();
            mockMovieConceptsMapper.Setup(m => m.AreEqual(It.IsAny<IMovieConceptModel>(), It.IsAny<IMovieConcept>())).Returns(() => true);
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, mockMovieConceptsMapper.Object);
            mockMovieConceptsRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => new Mock<IMovieConcept>().Object);
            mockMovieConceptsRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Deactivate(1);
            // Assert
            mockMovieConceptsRepository.Verify(m => m.Deactivate(It.IsAny<IMovieConcept>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Deactivate_ByKey_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            var mockMovieConceptsMapper = new Mock<IMovieConceptMapper>();
            mockMovieConceptsMapper.Setup(m => m.AreEqual(It.IsAny<IMovieConceptModel>(), It.IsAny<IMovieConcept>())).Returns(() => true);
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, mockMovieConceptsMapper.Object);
            mockMovieConceptsRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => new Mock<IMovieConcept>().Object);
            mockMovieConceptsRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Deactivate("KING-STEPHEN");
            // Assert
            mockMovieConceptsRepository.Verify(m => m.Deactivate(It.IsAny<IMovieConcept>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Deactivate_ByID_ANonExistingEntity_Should_ThrowAnInvalidOperationException()
        {
            // Arrange
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            mockMovieConceptsRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => null);
            var mockMovieConceptsMapper = new Mock<IMovieConceptMapper>();
            mockMovieConceptsMapper.Setup(m => m.AreEqual(It.IsAny<IMovieConceptModel>(), It.IsAny<IMovieConcept>())).Returns(() => true);
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, mockMovieConceptsMapper.Object);
            // Act/Assert
            Assert.Throws<System.InvalidOperationException>(() => businessWorkflow.Deactivate(1));
        }

        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Deactivate_ByKey_ANonExistingEntity_Should_ThrowAnInvalidOperationException()
        {
            // Arrange
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            mockMovieConceptsRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => null);
            var mockMovieConceptsMapper = new Mock<IMovieConceptMapper>();
            mockMovieConceptsMapper.Setup(m => m.AreEqual(It.IsAny<IMovieConceptModel>(), It.IsAny<IMovieConcept>())).Returns(() => true);
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, mockMovieConceptsMapper.Object);
            // Act/Assert
            Assert.Throws<System.InvalidOperationException>(() => businessWorkflow.Deactivate("TEST"));
        }
        #endregion
        #region Remove
        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Remove_ByID_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            var mockMovieConceptsMapper = new Mock<IMovieConceptMapper>();
            mockMovieConceptsMapper.Setup(m => m.AreEqual(It.IsAny<IMovieConceptModel>(), It.IsAny<IMovieConcept>())).Returns(() => true);
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, mockMovieConceptsMapper.Object);
            mockMovieConceptsRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => new Mock<IMovieConcept>().Object);
            mockMovieConceptsRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Remove(1);
            // Assert
            mockMovieConceptsRepository.Verify(m => m.Remove(It.IsAny<IMovieConcept>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Remove_ByKey_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            var mockMovieConceptsMapper = new Mock<IMovieConceptMapper>();
            mockMovieConceptsMapper.Setup(m => m.AreEqual(It.IsAny<IMovieConceptModel>(), It.IsAny<IMovieConcept>())).Returns(() => true);
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, mockMovieConceptsMapper.Object);
            mockMovieConceptsRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => new Mock<IMovieConcept>().Object);
            mockMovieConceptsRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Remove("KING-STEPHEN");
            // Assert
            mockMovieConceptsRepository.Verify(m => m.Remove(It.IsAny<IMovieConcept>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact][Trait("Category", "MovieConcepts")]
        public void Verify_Remove_ANonExistingEntity_Should_ReturnTrue()
        {
            // Arrange
            var mockMovieConceptsRepository = MovieConceptsMockingSetup.DoMockingSetupForRepository();
            mockMovieConceptsRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => null);
            var businessWorkflow = new MovieConceptsBusinessWorkflow(mockMovieConceptsRepository.Object, new MovieConceptMapper());
            // Act
            var result = businessWorkflow.Remove("DOESNT-EXIST");
            // Assert
            Assert.Equal(true, result);
        }
        #endregion
    }
}
