// <auto-generated>
// <copyright file="People.IPersonAliasRepository.cs" company="clarityventures.com">
// Copyright (c) 2015 Clarity Ventures, Inc. All rights reserved.
// </copyright>
// <summary>Implements the PersonAliasesRepository Class.</summary>
// <remarks>This file was autogenerated using BusinessWorkflowsTestingFileMaster.tt in ComicVine.API.BusinessWorkflows.Testing\BusinessWorkflows\CodeGenerator</remarks>
// </auto-generated>
namespace ComicVine.API.Testing.BusinessWorkflows.People
{
    using System.Collections.Generic;
    using API.BusinessWorkflows;
    using API.Mappings;
    using DataModel.Schema;
    using Interfaces.DataModels;
    using Interfaces.Mappers;
    using Interfaces.Models;
    using Interfaces.Repositories;
    using Interfaces.SearchModels;
    using Models;
    using Moq;
    using Xunit;

    public static class PersonAliasesMockingSetup
    {
        public static Mock<IPersonAliasModel> DoMockingSetupForPersonAliasModel(int idReturnValue = 0, string name = "Stephen King")
        {
            var mockPersonAliasModel = new Mock<IPersonAliasModel>();
            // Mock Functions
            mockPersonAliasModel.Setup(m => m.Id).Returns(() => idReturnValue);
            mockPersonAliasModel.Setup(m => m.Active).Returns(() => true);
            mockPersonAliasModel.Setup(m => m.CustomKey).Returns(() => "KING-STEPHEN");
            mockPersonAliasModel.Setup(m => m.ApiDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockPersonAliasModel.Setup(m => m.SiteDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockPersonAliasModel.Setup(m => m.CreatedDate).Returns(() => new System.DateTime(2015, 10, 1));
            mockPersonAliasModel.Setup(m => m.UpdatedDate).Returns(() => null);
            mockPersonAliasModel.Setup(m => m.Name).Returns(() => name);
            mockPersonAliasModel.Setup(m => m.ShortDescription).Returns(() => "short");
            mockPersonAliasModel.Setup(m => m.Description).Returns(() => "long");
            // <None>
            // Related Objects
            mockPersonAliasModel.Setup(m => m.PersonId).Returns(() => 1);
            mockPersonAliasModel.Setup(m => m.Person).Returns(() => new PersonModel());
            // Associated Objects
            // <None>
            // Return
            return mockPersonAliasModel;
        }

        public static Mock<IPersonAlias> DoMockingSetupForPersonAlias(int idReturnValue = 0, string name = "Stephen King")
        {
            var mockPersonAlias = new Mock<IPersonAlias>();
            // Mock Functions
            mockPersonAlias.Setup(m => m.Id).Returns(() => idReturnValue);
            mockPersonAlias.Setup(m => m.Active).Returns(() => true);
            mockPersonAlias.Setup(m => m.CustomKey).Returns(() => "KING-STEPHEN");
            mockPersonAlias.Setup(m => m.ApiDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockPersonAlias.Setup(m => m.SiteDetailUrl).Returns(() => "/TEST/KING-STEPHEN");
            mockPersonAlias.Setup(m => m.CreatedDate).Returns(() => new System.DateTime(2015, 10, 1));
            mockPersonAlias.Setup(m => m.UpdatedDate).Returns(() => null);
            mockPersonAlias.Setup(m => m.Name).Returns(() => name);
            mockPersonAlias.Setup(m => m.ShortDescription).Returns(() => "short");
            mockPersonAlias.Setup(m => m.Description).Returns(() => "long");
            // <None>
            // Related Objects
            mockPersonAlias.Setup(m => m.PersonId).Returns(() => 1);
            mockPersonAlias.Setup(m => m.Person).Returns(() => new Person());
            // Associated Objects
            // <None>
            // Return
            return mockPersonAlias;
        }

        public static Mock<IPersonAliasesRepository> DoMockingSetupForRepository()
        {
            var mockPersonAliasesRepository = new Mock<IPersonAliasesRepository>();
            // Mock Functions
            mockPersonAliasesRepository.Setup(m => m.Get(It.IsAny<int>()))
                .Returns(() => new Mock<IPersonAlias>().Object);
            mockPersonAliasesRepository.Setup(m => m.Get(It.IsAny<string>()))
                .Returns(() => new Mock<IPersonAlias>().Object);
            mockPersonAliasesRepository.Setup(m => m.List)
                .Returns(() => new Mock<List<IPersonAlias>>().Object);
            mockPersonAliasesRepository.Setup(m => m.Search(It.IsAny<IPersonAliasSearchModel>(), It.IsAny<bool>()))
                .Returns(() => new Mock<List<IPersonAlias>>().Object);
            mockPersonAliasesRepository.Setup(m => m.Add(It.IsAny<IPersonAlias>()));
            mockPersonAliasesRepository.Setup(m => m.Remove(It.IsAny<IPersonAlias>()));
            mockPersonAliasesRepository.Setup(m => m.Deactivate(It.IsAny<IPersonAlias>()));
            mockPersonAliasesRepository.Setup(m => m.Update(It.IsAny<IPersonAlias>()));
            // Return
            return mockPersonAliasesRepository;
        }
    }

    public class PersonAliasesBusinessWorkflowsTests
    {
        #region Read
        [Fact]
        public void Verify_Get_ByID_Should_ReturnTheCorrectObjectType()
        {
            // Arrange
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, new PersonAliasMapper());
            // Act
            var person = businessWorkflow.Get(1);
            // Assert
            Assert.IsType<PersonAliasModel>(person);
        }

        [Fact]
        public void Verify_Get_ByKey_Should_ReturnTheCorrectObject()
        {
            // Arrange
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, new PersonAliasMapper());
            // Act
            var person = businessWorkflow.Get("KING-STEPHEN");
            // Assert
            Assert.IsType<PersonAliasModel>(person);
        }

        [Fact]
        public void Verify_Search_Should_ReturnAListOfPersonAliases()
        {
            // Arrange
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            var searchModel = new Mock<IPersonAliasSearchModel>();
            var mockPersonAliasesMapper = new Mock<IPersonAliasMapper>();
            mockPersonAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IPersonAliasModel>(), It.IsAny<IPersonAlias>())).Returns(() => true);
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, mockPersonAliasesMapper.Object);
            // Act
            businessWorkflow.Search(searchModel.Object);
            // Assert
            mockPersonAliasesRepository.Verify(m => m.Search(It.IsAny<IPersonAliasSearchModel>(), It.IsAny<bool>()), Times.Once);
        }

        [Fact]
        public void Verify_Search_AsListing_Should_ReturnAListOfPersonAliasesWithDataMatchingSearchParametersWithListingMapping()
        {
            // Arrange
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            var searchModel = new Mock<IPersonAliasSearchModel>();
            var mockPersonAliasesMapper = new Mock<IPersonAliasMapper>();
            mockPersonAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IPersonAliasModel>(), It.IsAny<IPersonAlias>())).Returns(() => true);
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, mockPersonAliasesMapper.Object);
            // Act
            businessWorkflow.Search(searchModel.Object, true);
            // Assert
            mockPersonAliasesRepository.Verify(m => m.Search(It.IsAny<IPersonAliasSearchModel>(), It.IsAny<bool>()), Times.Once);
        }
        #endregion
        #region Create
        [Fact]
        public void Verify_Create_Should_AddANewEntityObjectToTheDatabase()
        {
            // Arrange
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            mockPersonAliasesRepository.Setup(m => m.Search(It.IsAny<IPersonAliasSearchModel>(), It.IsAny<bool>()))
                .Returns(() => new Mock<List<IPersonAlias>>().Object);
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, new PersonAliasMapper());
            var model = PersonAliasesMockingSetup.DoMockingSetupForPersonAliasModel();
            // Act
            try { businessWorkflow.Create(model.Object); } catch { /* Ignored */ }
            // Assert
            mockPersonAliasesRepository.Verify(m => m.Add(It.IsAny<IPersonAlias>()), Times.Once);
        }
        [Fact]
        public void Verify_Create_WithDuplicateData_Should_NotAddAndReturnOriginal()
        {
            // Arrange
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            var mockPersonAlias = PersonAliasesMockingSetup.DoMockingSetupForPersonAlias(1);
            mockPersonAliasesRepository.Setup(m => m.Search(It.IsAny<IPersonAliasSearchModel>(), It.IsAny<bool>()))
                .Returns(() => new List<IPersonAlias> { mockPersonAlias.Object } );
            mockPersonAliasesRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => mockPersonAlias.Object);
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, new PersonAliasMapper());
            var model = PersonAliasesMockingSetup.DoMockingSetupForPersonAliasModel();
            // Act
            try { businessWorkflow.Create(model.Object); }
            catch { /* ignored, the Get call at the end doesn't work because don't get a real entity with id on it */ }
            // Assert
            mockPersonAliasesRepository.Verify(m => m.Add(It.IsAny<IPersonAlias>()), Times.Never);
        }
        #endregion
        #region Update
        [Fact]
        public void Verify_Update_Should_SetUpdatedDate()
        {
            // Arrange
            var mockPersonAlias = PersonAliasesMockingSetup.DoMockingSetupForPersonAlias(1);
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            mockPersonAliasesRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => mockPersonAlias.Object);
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, new PersonAliasMapper());
            var expectedName = "Stephen King (2)";
            var model = PersonAliasesMockingSetup.DoMockingSetupForPersonAliasModel(1, expectedName);
            // Act
            businessWorkflow.Update(model.Object);
            // Assert
            mockPersonAlias.Verify(m => m.UpdatedDate, Times.Once);
        }
        [Fact]
        public void Verify_Update_WithDuplicateData_Should_NotAddAndReturnOriginal()
        {
            // Arrange
            var entity = PersonAliasesMockingSetup.DoMockingSetupForPersonAlias(1);
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            mockPersonAliasesRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => entity.Object);
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, new PersonAliasMapper());
            var model = PersonAliasesMockingSetup.DoMockingSetupForPersonAliasModel(1);
            IPersonAliasModel result = null;
            // Act
            try { result = businessWorkflow.Update(model.Object); }
            catch { /* ignored, the Get call at the end doesn't work because don't get a real entity with id on it */ }
            // Assert
            Assert.NotNull(result);
            Assert.Equal("Stephen King", result.Name);
            Assert.Equal("/TEST/KING-STEPHEN", result.ApiDetailUrl);
            Assert.Null(result.UpdatedDate);
        }
        #endregion
        #region Deactivate
        [Fact]
        public void Verify_Deactivate_ByID_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            var mockPersonAliasesMapper = new Mock<IPersonAliasMapper>();
            mockPersonAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IPersonAliasModel>(), It.IsAny<IPersonAlias>())).Returns(() => true);
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, mockPersonAliasesMapper.Object);
            mockPersonAliasesRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => new Mock<IPersonAlias>().Object);
            mockPersonAliasesRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Deactivate(1);
            // Assert
            mockPersonAliasesRepository.Verify(m => m.Deactivate(It.IsAny<IPersonAlias>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact]
        public void Verify_Deactivate_ByKey_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            var mockPersonAliasesMapper = new Mock<IPersonAliasMapper>();
            mockPersonAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IPersonAliasModel>(), It.IsAny<IPersonAlias>())).Returns(() => true);
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, mockPersonAliasesMapper.Object);
            mockPersonAliasesRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => new Mock<IPersonAlias>().Object);
            mockPersonAliasesRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Deactivate("KING-STEPHEN");
            // Assert
            mockPersonAliasesRepository.Verify(m => m.Deactivate(It.IsAny<IPersonAlias>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact]
        public void Verify_Deactivate_ByID_ANonExistingEntity_Should_ThrowAnInvalidOperationException()
        {
            // Arrange
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            mockPersonAliasesRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => null);
            var mockPersonAliasesMapper = new Mock<IPersonAliasMapper>();
            mockPersonAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IPersonAliasModel>(), It.IsAny<IPersonAlias>())).Returns(() => true);
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, mockPersonAliasesMapper.Object);
            // Act/Assert
            Assert.Throws<System.InvalidOperationException>(() => businessWorkflow.Deactivate(1));
        }

        [Fact]
        public void Verify_Deactivate_ByKey_ANonExistingEntity_Should_ThrowAnInvalidOperationException()
        {
            // Arrange
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            mockPersonAliasesRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => null);
            var mockPersonAliasesMapper = new Mock<IPersonAliasMapper>();
            mockPersonAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IPersonAliasModel>(), It.IsAny<IPersonAlias>())).Returns(() => true);
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, mockPersonAliasesMapper.Object);
            // Act/Assert
            Assert.Throws<System.InvalidOperationException>(() => businessWorkflow.Deactivate("TEST"));
        }
        #endregion
        #region Remove
        [Fact]
        public void Verify_Remove_ByID_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            var mockPersonAliasesMapper = new Mock<IPersonAliasMapper>();
            mockPersonAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IPersonAliasModel>(), It.IsAny<IPersonAlias>())).Returns(() => true);
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, mockPersonAliasesMapper.Object);
            mockPersonAliasesRepository.Setup(m => m.Get(It.IsAny<int>())).Returns(() => new Mock<IPersonAlias>().Object);
            mockPersonAliasesRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Remove(1);
            // Assert
            mockPersonAliasesRepository.Verify(m => m.Remove(It.IsAny<IPersonAlias>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact]
        public void Verify_Remove_ByKey_Should_DeactivateTheObjectAndReturnTrue()
        {
            // Arrange
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            var mockPersonAliasesMapper = new Mock<IPersonAliasMapper>();
            mockPersonAliasesMapper.Setup(m => m.AreEqual(It.IsAny<IPersonAliasModel>(), It.IsAny<IPersonAlias>())).Returns(() => true);
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, mockPersonAliasesMapper.Object);
            mockPersonAliasesRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => new Mock<IPersonAlias>().Object);
            mockPersonAliasesRepository.Setup(m => m.SaveChanges()).Returns(() => true);
            // Act
            var result = businessWorkflow.Remove("KING-STEPHEN");
            // Assert
            mockPersonAliasesRepository.Verify(m => m.Remove(It.IsAny<IPersonAlias>()), Times.Once);
            Assert.Equal(true, result);
        }

        [Fact]
        public void Verify_Remove_ANonExistingEntity_Should_ReturnTrue()
        {
            // Arrange
            var mockPersonAliasesRepository = PersonAliasesMockingSetup.DoMockingSetupForRepository();
            mockPersonAliasesRepository.Setup(m => m.Get(It.IsAny<string>())).Returns(() => null);
            var businessWorkflow = new PersonAliasesBusinessWorkflow(mockPersonAliasesRepository.Object, new PersonAliasMapper());
            // Act
            var result = businessWorkflow.Remove("DOESNT-EXIST");
            // Assert
            Assert.Equal(true, result);
        }
        #endregion
    }
}
