// <auto-generated>
// <copyright file="dbo.IConceptRepository.cs" company="clarityventures.com">
// Copyright (c) 2015 Clarity Ventures, Inc. All rights reserved.
// </copyright>
// <summary>Implements the ConceptsRepository Class.</summary>
// <remarks>This file was autogenerated using RepositoryFileMaster.tt in ComicVine.API.Repositories\Repositories\CodeGenerator</remarks>
// </auto-generated>
namespace ComicVine.API.Repositories//.dbo
{
    using System.Collections.Generic;
    using System.Linq;
    using DataModel.Schema;
    using Interfaces.DataModels;
    using Interfaces.Repositories;
    using Interfaces.SearchModels;

    public class ConceptsRepository : RepositoryBase, IConceptsRepository
    {
        public ConceptsRepository(object context) : base(context) { }

        public void Add(IConcept entity)
        {
            Context.Concepts.Add((Concept)entity);
        }

        public void Remove(IConcept entity)
        {
            Context.Concepts.Remove((Concept)entity);
        }

        public void Deactivate(IConcept entity)
        {
            entity.Active = false;
            Update(entity);
        }

        public void Update(IConcept entity)
        {
            Context.SetModified(entity);
        }

        public IConcept Get(int id)
        {
            return Context.Concepts.FirstOrDefault(r => r.Id == id);
        }

        public IConcept Get(string key)
        {
            return Context.Concepts.FirstOrDefault(r => r.CustomKey == key);
        }

        public IEnumerable<IConcept> List => Context.Concepts;

        public IEnumerable<dynamic> Search(IConceptSearchModel searchModel, System.Func<IConcept, dynamic> selectStatement, bool requireActive = true)
        {
            return SearchCommon(searchModel, requireActive)
                .Select(selectStatement);
        }

        public IEnumerable<IConcept> Search(IConceptSearchModel searchModel, bool requireActive = true)
        {
            return SearchCommon(searchModel, requireActive);
        }

        // ReSharper disable once ReturnTypeCanBeEnumerable.Local
        // ReSharper disable once SuggestBaseTypeForParameter
        private IQueryable<IConcept> SearchCommon(IConceptSearchModel searchModel, bool requireActive)
        {
            return Context.Concepts
                .FilterByBaseFilters(searchModel, requireActive)
                .FilterByNameableBaseFilters(searchModel)
                .FilterByPaging(searchModel.Paging);
        }
    }

    public static partial class ConceptSearchExtensions
    {
    } // end ConceptSearchExtensions
}
