// <auto-generated>
// <copyright file="Objects.IObjectVolumeRepository.cs" company="clarityventures.com">
// Copyright (c) 2015 Clarity Ventures, Inc. All rights reserved.
// </copyright>
// <summary>Implements the ObjectVolumesRepository Class.</summary>
// <remarks>This file was autogenerated using RepositoryFileMaster.tt in ComicVine.API.Repositories\Repositories\CodeGenerator</remarks>
// </auto-generated>
namespace ComicVine.API.Repositories//.Objects
{
    using System.Collections.Generic;
    using System.Linq;
    using DataModel.Schema;
    using Interfaces.DataModels;
    using Interfaces.Repositories;
    using Interfaces.SearchModels;

    public class ObjectVolumesRepository : RepositoryBase, IObjectVolumesRepository
    {
        public ObjectVolumesRepository(object context) : base(context) { }

        public void Add(IObjectVolume entity)
        {
            Context.ObjectVolumes.Add((ObjectVolume)entity);
        }

        public void Remove(IObjectVolume entity)
        {
            Context.ObjectVolumes.Remove((ObjectVolume)entity);
        }

        public void Deactivate(IObjectVolume entity)
        {
            entity.Active = false;
            Update(entity);
        }

        public void Update(IObjectVolume entity)
        {
            Context.SetModified(entity);
        }

        public IObjectVolume Get(int id)
        {
            return Context.ObjectVolumes.FirstOrDefault(r => r.Id == id);
        }

        public IObjectVolume Get(string key)
        {
            return Context.ObjectVolumes.FirstOrDefault(r => r.CustomKey == key);
        }

        public IEnumerable<IObjectVolume> List => Context.ObjectVolumes;

        public IEnumerable<dynamic> Search(IObjectVolumeSearchModel searchModel, System.Func<IObjectVolume, dynamic> selectStatement, bool requireActive = true)
        {
            return SearchCommon(searchModel, requireActive)
                .Select(selectStatement);
        }

        public IEnumerable<IObjectVolume> Search(IObjectVolumeSearchModel searchModel, bool requireActive = true)
        {
            return SearchCommon(searchModel, requireActive);
        }

        // ReSharper disable once ReturnTypeCanBeEnumerable.Local
        // ReSharper disable once SuggestBaseTypeForParameter
        private IQueryable<IObjectVolume> SearchCommon(IObjectVolumeSearchModel searchModel, bool requireActive)
        {
            return Context.ObjectVolumes
                .FilterByBaseFilters(searchModel, requireActive)
                .FilterByPaging(searchModel.Paging);
        }
    }

    public static partial class ObjectVolumeSearchExtensions
    {
    } // end ObjectVolumeSearchExtensions
}
